setup-git-sdk.bat
Due to the requirement to run post install scripts, the pacman -Syu
command cannot be run in the windows cmd window. Only the initial
msys2-runtime update should be run here.
=> changed initial pacman command

pacman-mirror.sh, setup-git-sdk.bat
So far, we (ab-)used a repository on GitHub to serve a Pacman repository. However, it is much better to use Bintray for that, as its mission is to deliver binaries. To do so, we need new tooling.
With the `pacman-mirror.sh` script added in this Pull Request, one can perform a `fetch` to initialize and update a local mirror of the Pacman repository, a `add <file>...` to add packages to the local mirror, and a `push` to index and (incrementally) upload the local files to Bintray.
=> Add tooling to work with the Pacman repository on Bintray

vimrc
By default `VIM` has no access to the systems clipboard under windows. The
setting `set clipboard=unnamed` will grant this access by default. This
behavior is something that IMHO many endusers would expect. See also this
posting in the `VIM` wiki: http://vim.wikia.com/wiki/Easy_pasting_to_Windows_applications
=> vim-clipboard-mode

pacman-mirror.sh
Our current layout differentiates only between architectures, no longer between msystems. Let's adjust the `pacman-mirror.sh` script to reflect that.
=> Adjust Pacman mirror script to current layout

gitconfig
Added a `default-gitconfig`. This file will be parsed by the `git-extra`
`PKGBUILD` file. The content will then be written in the respective
location based on the `MinGW` system (either `mingw32` or `mingw64`) installed.
=> default-gitconfig

git-extra/PKGBUILD
The splitup of the package file and the source was not such a good idea.
It was decided that the package file should be placed with the source
files. The `PKGBUILD` was adapted to handle the source files relative to
its location. The old location of this packe was in the
https://github.com/git-for-windows/msys2-packages repository.
Notes:
* This is for https://github.com/git-for-windows/git/issues/31
* Before the first build you need to run `touch git-extra.install`. If you dont do that, `makepkg` will complain about the `git-extra.install` file being missing.
=> git-extra: Relocation of the git-extra package

git-extra/git-prompt.sh
To distinguish between the working directory and the current git branch
the output of the `__git_ps1` call should be in a different color than the
rest of the prompt.
This is more like a proposal. If you feel this is unnecessary and is up to the end user in general that's fine. The default color is of course debatable.
=> Proposal: Modify output color of `__git_ps1` call

git-extra/git-prompt.sh
This makes color display correctly for programs that do not explicitly set
it but rely on the default color to be the current color.
=> git-prompt: Reset to default color after changing it for the branch name

net-installer/setup-git-sdk.bat
The install of `pacman` has a dependency for `gettext`. The `gettext`
package seems to fail with its post install script if the `info` package
is not installed. So to overcome this unresolved dependency, just install
the required package so that the post install script will succeed.
=> net-installer: Dependency fixes

portable/git-bash.bat.in
The `git-bash.bat` can not handle setups that were installed in a path
with a space in it. According to `help start` you are providing a title if
you use quotes. Because of this a dummy title must be provided to quote
the path to the console application.
=> portable-release: handle spaces in install path

portable/release.sh
There may be endusers that require more than the default shipped
components. At least give them a chance to ship it themselfs. This can even
be used to manage different bundles.
Think of a *core* package, e.g. `PortableGit-2.3.3.7z.exe` and an
additional package, e.g. `PortableGit-2.3.3-git-svn.7z.exe`. The first
would be created with `./release.sh 2.3.3` and the second would be created
with `./release.sh 2.3.3-git-svn subversion`.
=> portable-release: optional components support

net-installer/setup-git-sdk.bat
Since the *Git for Windows SDK* should provide functionality to build git
it should also provide all required packages to build the git doc.
Building doc is needed when shipping the git mingw package lets just
install those reuqirements too then.
=> net-installer: install requirements to build doc

git-extra/PKGBUILD, git-extra/env.sh
This behavior was present in the *msysgit* version of the `/etc/profile`
file. The `git-extra` package now adds a `homepath.sh` into the
`/etc/profile.d` directory to restore the behavior in the *MSYS2*
environment.
This *should* resolve https://github.com/git-for-windows/git/issues/57.
=> build-extra: add $HOME/bin to path

installer/install.iss.in, installer/release.sh
The generation of files to be shipped by the installer was significantly
improved by using a `sed` call. Also the `release.sh` is a little more
chatty now. The git tag is now only done if the tag does not exists
already. There were some syntax errors in the `installer.iss.in` file
that were squashed.
Helped-by: Johannes Schindelin <johannes.schindelin@gmx.de>
=> installer: syntax fixes and performance improvements

git-extra/PKGBUILD, git-extra/inputrc
This brings Git Bash's input and completion behavior in line with the
previous msysGit-based releases.
Fixes git-for-windows/git#62.
=> git-extra: Add inputrc

installer/install.iss.in
The old implementation did not work because every builtin was copied
to the toplevel directory. So this commit adapts the hardlink
creation to the following algorithm:
```
copy mingw??\libexec\git-core\git-log tmp\git-wrapper.exe
foreach builtin
if file_exists(mingw??\bin\builtin) then
delete mingw??\bin\builtin
if !create_hardlink(mingw??\bin\builtin) then
copy \tmp\git-wrapper.exe mingw??\bin\builtin
fi
fi
if file_exists(mingw??\libexec\builtin) then
delete mingw??\libexec\builtin
if ! create_hardlink(mingw??\libexec\builtin) then
copy \tmp\git-wrapper.exe mingw??\libexec\builtin
fi
fi
hcaerof
```
=> installer: hardlink creation reworked

installer/release.sh
To have a working ssh we need to ship that file too. Otherwise OpenSSH
will look in `/home/<username>/.ssh/` for the configuration. But we need
it to look in the windows home dir.
=> installer: ship `nsswitch.conf` too

installer/HowToRelease.txt, installer/ReleaseNotes.rtf
Adapted the release notes for the upcoming first *Git for Windows*
release. Furthermore the instructions to build and deploy a new upstream
release were adapted to the current process. That process is described in
the `HowToRelease.txt` file.
=> installer: Prepare release notes and documentation

installer/install.iss.in
The core.fscache config option provides a significant performance boost,
but it's still experimental. Since wider use can help flush out any
issues and push this from being experimental to production-ready, this
adds a page to the installer advising users of the setting's existence
and allowing them to enable it.
=> installer: Add installer page for performance tweaks

make-file-list.sh
These aren't used by Git for Windows, as we don't create the user's home
directory.
=> make-file-list: Exclude skel files

git-extra/inputrc
These are imported from MSYS2, except for the Mintty-specific macros.
=> git-extra: Add key mappings to inputrc

git-extra/git-extra.install.in
When checking for the https fix the script checks for every valid
comination to be patched. Since those packages are not installed on every
system lets not worry the user when updating `git-extra`.
=> git-extra: silence missing package error

net-installer/setup-git-sdk.bat
The fix for this is upstream [1] and the binaries are available, too [2].
[1] https://github.com/Alexpux/MINGW-packages/pull/570
[2] http://sourceforge.net/projects/msys2/files/REPOS/MINGW/
=> net-installer: Remove ca-certificate installation work-around

net-installer/setup-git-sdk.bat
Windows' "MKDIR creates any intermediate directories in the path, if
needed", so just suppress the "A subdirectory or file a already exists"
message eventually. Also ensure to create the "dev" directories in the
installation directory in case setup-git-sdk.bat was called from another
directory.
=> Simplify Windows MKDIR calls a bit

net-installer/release.sh, portable/release.sh
The user does not need to append .exe to the file name, that has already
been done.
=> Remove a mistakable comment from the release.sh scripts

.gitignore, portable/root/README.portable
It appears the README has diverged from the packaged portable files. Instead of `git-bash.bat` and `git-cmd.bat` existing, it is now `git-bash.exe` and `git-cmd.exe` in PortableGit-2.3.5.8-dev-preview-64-bit.
=> Replace usage of .bat with .exe

portable/release.sh
Portable applications should not be installed to Program Files. `%%S`
expands to the folder containing the self-extracting archive.
=> portable: Install Portable Git to a portable directory

portable/release.sh
In response to @sschuberth's [comment](https://github.com/git-for-windows/build-extra/pull/45#discussion_r29124904).
=> portable: Remove unused PROGRAMFILESENV variable

installer/install.iss.in
After copying the `git-log.exe` to the `tmp` directory for copying the
different `builtins` the temporary file is never cleaned up. This cleanup
call is now issued properly.
This fixes git-for-windows/git#114
=> installer: remove temporary `git-wrapper.exe`

installer/ReleaseNotes.md
bump the release notes to version 2.3.6. The meantioned fixes in the
release website on github were included.
This fixes git-for-windows/git#115
=> installer: updated release notes

git-extra/99-post-install-cleanup.post, git-extra/PKGBUILD, installer/install.iss.in, make-file-list.sh, portable/release.sh
This pull request adds the useful post-install scripts to the release packages and ensures that they are executed once after installation/extraction, at which point they are deleted.  Deletion is not done if `msys2.ico` is in the root directory, as that is (at present) a reliable indicator that we're in the SDK, and the post-install scripts need to be in place for the packages to be made.
Resolves git-for-windows/git#111.
=> Include post-install scripts and run after installation

installer/install.iss.in
Before trying to set the selected config values in the installer the code
now checks if the system wide git config exists. If that is not the case
the installer copies the shipped config to `%PROGRAMDATA%\Git\config` and
then tries to alter it as choosen by the user.
The shipped gitconfig is deleted after checking if the system wide git
config already exists.
=> installer: honor `%PROGRAMDATA%\Git\config`

installer/install.iss.in
`%1` expands to the short name of the file, rather than the directory
the file is contained in, so `--cd=%1` fails when `git-bash.exe` tries
to change the working directory to a file. `%w` expands to the file's
containing directory and `%L` expands to the long name of the file.
Additionally, this sets the `ChangesAssociations` flag to `yes`, so that
Explorer will refresh the system's file association information after
the install. It also changes the `DropHandler` to the WSH `DropHandler`,
which sends long file names instead of short file names, and forces
update of the command string.
Fixes git-for-windows/git#120.
Helped-by: @Animeye
=> installer: Fix .sh file association

installer/install.iss.in
Invoking `git-bash.exe` to run the post-install scripts results in a
mintty window appearing, even when invoked with `SW_HIDE`. Invoking bash
directly avoids this.
Fixes git-for-windows/git#126.
=> installer: Invoke bash directly for post-install

installer/install.iss.in
When installing the system wide config into `%PROGRAMDATA\Git\config` make
sure that the `http.sslCAInfo` config entry is expanded to the full path
of the new git installation.
Only try this if there is not yet an existing `config` file. We don't want
to override pre existing settings.
=> installer: expand path when setting `http.sslCAInfo`

make-file-list.sh
As per the discussion in https://groups.google.com/forum/#!topic/git-for-windows/jerxhdoS-20.
Adding tar in the list of packaged GNU utilities. This to increase compatibility with users coming from msysgit 1.x and causes a slight increase in filesize.
Comparing the Portable built package:
Build | Installer size (kb) | Unpacked size (kb)
------ | ---------------------- | ----------------------
Without tar | 48720 | 400196
With tar | 49094 | 402516
=> add tar to list of packaged GNU utilities

installer/install.iss.in
Make installer copy DLLs found in `mingw64/bin` to `mingw64/libexec/git-core` if they conflicts with a DLL in `%SystemRoot%/System32`. This prevents for example `git-remote-https.exe` (in `libexec/git-core`) to pick up a pre-existing OpenSSH DLL (`ssleay32.dll`) in `%SystemRoot%/System32` that could be present on user's machine.
See https://github.com/git-for-windows/git/issues/145.
=> Avoid git for windows DLLs conflicts with system ones

make-file-list.sh
It is required by `git mergetool`.
This fixes https://github.com/git-for-windows/git/issues/163
=> Include `diff.exe` into the installers

installer/ReleaseNotes.md
Git will not commit these files because they are ambiguous. Closes #216.
=> Add known issue of truncated DOS-style filenames

installer/ReleaseNotes.md
The release notes of the latest installer are still referring to the
previous git version. Lets fix this.
=> installer: correction in release notes

git-extra/PKGBUILD, git-extra/bash_profile.sh
This is a conversion of commit ebf60bd55e88693ceb73dea49783b5965cd2619b
originally created in the msysgit project. The new file in the `profile.d`
folder will try to create an appropriate `~/.bash_profile` file if it
encounterns a `~/.bashrc` file.
This fixes git-for-windows/git#191
Helped-by: Arlo Louis <MailToArlo@gmail.com>
=> git-extra: fix call of `~/.bashrc`

git-extra/git-extra.install.in
If `bash` is called without the `--login` function, the `git-prompt.sh` in
the `profile.d` directory will not get sourced. Lets fix this behavior by
explicitly checking if this bash instance was called without the `--login`
argument and if so call the `git-prompt.sh`.
This fixes git-for-windows/git#290
=> git-extra: add git-prompt check to bash.bashrc

installer/install.iss.in
The wizard page for choosing your terminal emulator truncates some words. See examples in the screenshot below (I am using Windows 8.1, 1920x1080, not sure it matters):
Would this work? I haven't tried building a new installer and running it. Will give it a try if needed.
=> installer: shorten text wrap for terminal captions

make-file-list.sh
Lets include the newly created package in the installer. Note that the
huble maintainer needs to build, release and install that package so that
it will indeed be picked up.
This fixes git-for-windows/git#293
=> connect: include new connect package

installer/ReleaseNotes.md, make-file-list.sh
https://github.com/git-for-windows/git/issues/221
=> Include the patch package

git-extra/aliases.sh
This patch adds support for a couple of interactive consoles that users
invariably want to run in their Git Bash (despite our clear warning in the
release notes and the installer; Who reads text anyways?).
Of course, the list is non-exhaustive. The idea is that we can extend this
whenever needed. Or even better: users can extend this as needed and make
a Pull Request, in true Open Source style facilitated by... *drumroll*...
Git.
This fixes https://github.com/git-for-windows/git/issues/399 and
https://github.com/git-for-windows/git/issues/400
=> git-extra: add aliases to support interactive consoles in mintty

post-install.bat
Since we do not run the post-install scripts in a full login shell
anymore, `/etc/profile` has no chance of defining the `SYSCONFDIR`
before `03-tab.post` wants to use it.
So let's just hard-code it in `post-install.bat`.
This fixes https://github.com/git-for-windows/git/issues/405
=> post-install.bat: give 03-mtab a chance to write to the correct path

installer/install.iss.in
The newly introduces registry key
HKEY_LOCAL_MACHINE\Software\GitForWindows
will now be created and it will contain three values: CurrentVersion,
InstallPath and LibexecPath.
The intention is to support third-party tools' installers so that e.g.
additional remote or credential helpers can easily be installed into the
correct location.
=> installer: record version and some paths in the registry

installer/install.iss
Allows the installer to be run with normal user permissions again.
Fixes git-for-windows/git#497
=> installer: Change installer privileges to 'lowest'

.gitignore, archive/release.sh, archive/root/etc/hosts, archive/root/etc/networks, archive/root/etc/protocols, archive/root/etc/services
Adds an `archive/release.sh` script, similar to `portable/release.sh`. The resulting .tar.bz2 archive has all post-install steps pre-applied so the Git for Windows installation is ready for use right after extraction.
This is for issue git-for-windows/git#513
=> Add script for building .tar.bz2 release

sdk-installer/setup-git-sdk.bat
The issue described in commit 918a119f993fe5d43638e11efd1f5897cc891bfc
also applies to 64-bit systems, at least for two different computers
used by this developer.
Signed-off-by: Dillon Kuehner <astrophizz@gmail.com>
=> Expand rebase workaround to all architectures

make-file-list.sh
column.exe is included for the benefit of https://github.com/tj/git-extras
which uses column.exe in git line-summary, git summary and git ignore-io.
It's a 25kb file with no additional dependencies (msys-intl-8.dll,
msys-iconv-2.dll and msys-2.0.dll are all included already). From the
util-linux package...
Closes: https://github.com/git-for-windows/git/issues/586
=> Add column.exe to the installed files

installer/install.iss
Icons added to Windows Explorer integration
In Windows 7 and above there is a possibility to define an icon for
context menu items. To benefit from this, the Icon property has been
set for the provided entries.
This fixes https://github.com/git-for-windows/git/issues/582
=> Icons added to Windows Explorer integration

installer/install.iss, installer/release.sh
It's just a very nice visual indicator for the user that things are about to get real.
=> Switch the "Next" button's label to "Install" on the last wizard page before installation

installer/install.iss
This feature really stood the test of time by now, and the wish to
enable it by default has been mentioned quite a couple of times to the
Git for Windows maintainer. Let's make it so.
=> installer: enable fscache by default

installer/install.iss
Many Windows users are very familiar with `cmd.exe` and not really with
the Bash at all. Requiring them to call `Git CMD` explicitly just to be
able to use Git for Windows from their favorite command-line is not
really helpful, in particular when the command-line is launched from
within other software.
So let's just switch the default to adding the `git.exe` (and gitk.exe
and git-gui.exe`) to the PATH.
=> installer: switch the default PATH option to 'CMD'

installer/install.iss
=> installer: offer to launch "Git Bash" right away

make-file-list.sh, sdk-installer/setup-git-sdk.bat
@dscho This is my first stab at integrating ssh-pageant support into Git for Windows [[Issue #683]](https://github.com/git-for-windows/git/issues/683). This has been working flawlessly for me under Windows 7 64-bit, provided that the _ssh-pageant_ package was already installed (performed via `pacman -Sy ssh-pageant`) when the installer/portable was built. The reason for request being marked as DO NOT MERGE YET is because I'm unsure if additional action is required, in order to ensure the package is present (by default) when you make a build... my guess is that it needs to somehow be tagged as "install by default" for the SDK, or similar.
The benefit of this integration is that it actually helps us to become _less_ reliant on PuTTY, within the specific context of Git for Windows. For those …
=> Integrate ssh-pageant

.gitignore, nuget/GitForWindows.nuspec.in, nuget/Install.ps1, nuget/release.sh
We steal heavily from ourselves here...
Please note that the Install.ps1 script is only called if the NuGet
package is installed inside Visual Studio (and not if installed via
nuget.exe; this is a bug in nuget.exe as of time of writing).
Therefore, the user should still call tools\post-install.bat manually
or start tools\git-bash.exe once before doing anything else, if
nuget.exe is used to install this package.
=> Support generating NuGet packages of Git for Windows

git-lfs/.gitignore, git-lfs/PKGBUILD, git-lfs/git-lfs.install
There's likely some improvements to do here, but opening this early for feedback:
```
brendanforster@SHIFTKEYDE8B MINGW32 /usr/src/build-extra/git-lfs (add-support-for-git-lfs)
$ /mingw32/bin/git-lfs.exe
bash: /mingw32/bin/git-lfs.exe: cannot execute binary file: Exec format error
brendanforster@SHIFTKEYDE8B MINGW32 /usr/src/build-extra/git-lfs (add-support-for-git-lfs)
$ file /mingw32/bin/git-lfs.exe
/mingw32/bin/git-lfs.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
```
cc @dscho as we discussed last week
cc @technoweenie just cause
=> Add support for Git LFS

msi/GitProduct.wxs, msi/release.sh
The simple solution using `PersonalFolder` during install means the
Git shortcuts all use "My Documents" folder for the user that
installed Git for Windows. Unfortunately, that means subsequent users
attempt to start in the installing user's "My Documents" folder.
Obviously that is undersirable behavior at best and won't work at all
given folder permissions at worst.
So instead we'll use our INSTALLFOLDER as the working folder and the
`--cd-to-home` argument to let the tools start in a reasonable folder.
Based on outstanding research by @fourpastmidnight
=> msi: Fix shortcut working folder for other users

edit-git-bash.c, msi/GitProduct.wxs, msi/release.sh, nuget/release.sh
This pull request teaches the MSI installer to respect the user's choice of terminal emulator: mintty or ConHost (i.e. the standard Windows Command Prompt DOS box).
This pull request also incorporates a few fixes to the MSI and NuGet `release.sh` scripts, aborting the creation of the installer or NuGet package if the Release Notes could not be generated.
=> msi: Respect user's choice of terminal emulator

git-extra/git-prompt.sh
The SDK installation, at some point, overwrites the /etc/bash.bashrc file
and now detects a $MSYS2_PS1 prompt as an alternative to setting a default
PS1 prompt. Any pre-prepared PS1 is overwritten.
Provide that alternate environment variable.
The Git-for-Windows installation does not use that version of the
/etc/bash.bashrc file, so is unaffected.
Signed-off-by: Philip Oakley <philipoakley@iee.org>
=> git-prompt: fully enable the PS1 prompt on the SDK

git-extra/astextplain, git-extra/git-extra.install, git-extra/gitattributes
The above file-types were added alongside the existing .doc/docx/dot
Word formats.
=> git-extra: add support for docm and dotm diffs

ReleaseNotes.md
Update the (G4W) Release Notes with an example of using the double slash, and also an example of the Windows drive letter conversion.
This is a fall out from my attempt to use `git apply <path>` to a patch which wasn't within the root path of the git bash invocation (neither my SDK install, nor my Program Files install). 
I could `cat` the file, but git said it didn't exist. (repeated below)
```
Philip@PhilipOakley MINGW32 /c/git-sdk-32/usr/src/build-extra (dslash)
$ git apply '/c/Documents and Settings/Philip/My Documents/git stuff/[PATCHv4] Documentation_ triangular workflow.eml'
fatal: can't open patch '/c/Documents and Settings/Philip/My Documents/git stuff/[PATCHv4] Documentation_ triangular workflow.eml': No such file or directory
Philip@PhilipOakley MINGW32 …
```
=> Double slash path conversion, and drive letter examples

mingw-w64-git-lfs/git-lfs.install
The same config is set via the `git lfs install` command:
https://github.com/git-lfs/git-lfs/blob/e029224251e2d8b134ee92f3cc00e001fdcbfb40/lfs/setup.go#L32-L35
However, I wonder if should rather use [`git lfs install --system`](https://github.com/git-lfs/git-lfs/blob/e029224251e2d8b134ee92f3cc00e001fdcbfb40/commands/command_install.go#L56) ?
--
This change is not tested. I just noticed the file and thought I could update it. I am pretty sure it works, though...
/cc @shiftkey
=> git-lfs: add config for more efficent filter-process protocol

please.sh
These descriptions markers make it possible to cut the
"test_remote_branch" log into "build", "test", and "after failed test"
sections. This is useful to print the sections in the appropriate steps
in the TravisCI run.
**Attention:**
I haven't tested this as I don't have the setup. But it should work 😄 
/cc @dscho
=> please.sh: print action description to console

installer/install.iss
Use the icon from the wrapper executable for the Windows Explorer
integration, this ensures that the executable and context menu show the
same icon, in addition to not depending on a separate file.
=> explorer integration: use icon from executable

installer/install.iss, mingw-w64-git-lfs/PKGBUILD
Because git-lfs is intended to run both through git.exe (e.g. 'git lfs',
generally when the user executes an LFS command manually) and as a
standalone executable (e.g. 'git-lfs', as run by the filters), git-lfs.exe
should reside as a top-level executable.
This prevents an issue where the user may have an older version of LFS
installed by itself and 'git-lfs' finds that version while 'git lfs' finds
the bundled version.
=> Move git-lfs binary back out of git-core

git-extra/git-prompt.sh
Allow to override the Git prompt by reading in
~/.config/git/git-prompt.sh, if it exists, as part of the default
/etc/profile.d/git-prompt.sh.
=> Allow to override the Git prompt (and mintty window title)

git-extra/git-extra.install, git-extra/git-extra.install.in
This is my initial attempt to add `getent` to the Git for Windows package, in order to address [issue #1226](https://github.com/git-for-windows/git/issues/1226). It seems to work exactly as expected for the 64-bit release on Windows 10, but I want to do some additional validation (portable and SDK installers, as well as the 32-bit variants) before considering it ready to merge... I probably won't have an opportunity to do this until Sunday.
The only downside I see thus far is that it increased the size of the installer binary by approximately 10 MB, which is roughly 20 percent. This might be enough of a jump to be problematic for folks with less-than-ideal connectivity speeds.
An alternate, potential fix would be to include just */usr/bin/getent* (along with any hard dependencies) instead …
=> Remove getent calls from /etc/bash.bashrc

sdk-installer/setup-git-sdk.bat
Just clone the latest commit of the source.
.git size of a full clone   : 143 MB (150,062,380 bytes)
.git size of a shallow clone: 7.52 MB (7,886,193 bytes)
=> sdk-installer: shallow clone the git source

git-extra/PKGBUILD, git-extra/git-update
A shell script that makes keeping Git for Windows up to date as simply as # git-update --yes
Compares what version is currently installed against the latest available release.
If versions differ, the bit matched installer is downloaded and run when confirmation to do so is given.
Discussed in Git issue https://github.com/git-for-windows/git/issues/1256
=> git-update - Keep Git for Windows up to date via the command-line

git-extra/git-prompt.sh
Seems like this limitation is artificial at this point (it's been there since the beginning of the repository).
Not updating `PKGBUILD` since `updpkgsums` showed other changes and I guess there's a different process to it.
=> git-extra: Allow non-ASCII characters from $PWD in window title

git-extra/inputrc
Provide the same command-line experience as in Linux
Ctrl+Left moves cursor a word backward
Ctrl+Right moves cursor a word forward
=> Enable Ctrl-Arrow backward forward words

post-install.bat, sdk-installer/setup-git-sdk.bat
A couple commits fixing 32-bit Windows msys-2.0.dll address range workarounds. Please read commit messages for more details.
=> Fix vars in bat files

installer/install.iss, make-file-list.sh
Nano is a lightweight text editor that most novices to the bash command line find easier to use than vim.
This PR adds the msys2 package of nano to the Git-for-Windows installer and adds an option
(opt-in) to the install process to set it as core.editor.
Nano has a small footprint (installed 2.28 MiB [1]) and only few dependencies that are already included in Git for Windows. According to my tests the size of the installer is only increased by ca. 100 KiB.
The PR has been created according to what @dscho has outlined in git-for-windows/git#1224
[1]:
```
$ pacman -Qi nano
Name            : nano
Version         : 2.8.7-1
Description     : Pico editor clone with enhancements
Architecture    : x86_64
URL             : https://www.nano-editor.org
Licenses        : GPL
Groups          : editors …
```
=> Add Nano editor

installer/install.iss
Adds the VisualStudioCode as edit option.  (https://github.com/git-for-windows/git/issues/1356)
VisualStudioCodePath: remove any %1 occurrance that comes from the registry.
VisualStudioCode command line options:  --wait
[Visual Studio Code](https://code.visualstudio.com/) is a really fantastic and popular free open source editor. (its MIT license, meaning, _Free as in Speech_)
It has a huge momentum and is rated as no.1 in quite a [lot of places](https://ourcodeworld.com/articles/read/200/top-7-best-free-web-development-ide-for-javascript-html-and-css).
Signed-off-by:  igorlino (Igor Jacy Lino Campista)
Thanks-to: @dscho 
Mentored-by: @dscho
=> Add VisualStudioCode as edit option

git-extra/git-update, installer/install.iss
As discussed in [Issue #1363](https://github.com/git-for-windows/git/issues/1363#issuecomment-356616531): the existing `git-update` behaviour, where no response is given if Git has already been validated as up-to-date in a previous check, has been moved behind a "--quiet" flag and added to the auto-update process.
=> Change to git-update behaviour when Git is up-to-date

installer/install.iss
Since _Git for Windows_ propagated the new url
`https://gitforwindows.org/` with the last release we sould also use that
new url inside the installer.
=> installer: Change app url used by installer

git-extra/PKGBUILD, git-extra/git.nanorc, git-extra/nanorc
Quite a while now _Git for Windows_ is given the users a choice to
select the `nano` editor over `vim` as the default one. So it should
feel natural to us to improve the user experience with this new default
editor.
This commit will add the `git.nanorc` file that is available on github
(https://github.com/scopatz/nanorc/blob/master/git.nanorc) to the
git-extra package. git-extra will install that syntax-highlighting file
to `/usr/share/nano` so that it will be globally available.
This leads us to the second improvement. `nano` comes with quite a lot
syntax-highlighting files already. But they are not enabled by default.
So this commit also adds a slightly modifed `nanorc` file to the
git-extra package. The file will be installed into the `/etc` folder
just like the `vimrc` file. The …
=> git-extra: Install nanorc and git.nanorc file

git-extra/PKGBUILD, git-extra/git-update, git-extra/git-update-git-for-windows, installer/install.iss, make-file-list.sh
In 1da13c5 (Keep Git for Windows up to date via the command-line,
2017-08-11) we added a command to download and install the latest
Git for Windows version. We called this command "git update".
Users, especially Git novices, could easily view the verb "update" as
Git version control operation. Fix the ambiguity by renaming it to
"self-upgrade".
=> rename "git update" to "git update-git-for-windows"

installer/install.iss
This addresses #1409
One strange thing in my fix may be the setting and unsetting of http.dummy variable. This is a work-around for Git config problem described here:
https://stackoverflow.com/questions/37147475/gitconfig-section-duplicates-everytime-i-set-a-preference
Without this trick the installer was leaving one empty [http] section. Everything else was working fine, but system config file looked ugly.
This is my first contribution to Git for Windows, please be forgiving :)
=> Don't set http.sslCAInfo for schannel

installer/install.iss
Support for git-lfs wrapping in `/cmd`, see git-for-windows/git#1503
=> installer: add the git-lfs wrapper to /cmd

git-extra/git-sdk.sh
* git-sdk: if a repo already exists, don't try to reinitialize it
* git-sdk: remove the shebang line
With these changes, I was able to actually build a new Git with `sdk build git`.
=> git-sdk fixes

make-file-list.sh
It is widely used nowadays
Signed-off-by: Orgad Shaneh <orgads@gmail.com>
=> Install xz

portable/root/README.portable
Almost three years ago, I edited `readme.portable` to document a command line switch. I made a mistake which I have discovered today. This pr fixes it. What can I say, sorry for the delay...
=> Fixed explanation of --cd-to-home

git-extra/astextplain, git-extra/git-extra.install, git-extra/gitattributes
dotx is the file format for Word templates which is already supported by
docx2txt.pl
This pull request was based on pull request #128 and issue #900
(git-for-windows/git). They added compatibility with docm and dotm files
=> git-extra: added support for dotx diffs

git-extra/git-sdk.sh
As per git-for-windows/git#1660 - In non-standard environments the $HOME environment variable may not point to the folder containing the Desktop folder, so use the "Known Folder" $USERPROFILE.
I'm not sure this 100% correct - Windows [has a whole API](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776911(v=vs.85).aspx) for discovering the correct location of the desktop folder, maybe the right way would be modifying the create-shortcut helper to find out the Desktop folder location by itself.
=> sdk create-desktop-icon: use $USERPROFILE instead of $HOME

git-extra/vimrc
Hi this branch changes some of the Vim settings. I tried to make the commits as granular as possible to make reviewing easier.
Currently some settings can be improved a bit, so I slightly changed them. I tried not to change them according to my personal taste and if I did, I mentioned it in the commit message (cursor block style, command line completion, ...) and those could then reverted if needed.
The rest should keep Vim more closely to Vims upstream repository, especially since it sources the defaults.vim file anyhow (currently overwriting some settings). 
Also I found comments beneficial, so I left a couple of more comments. One thing I did not know for sure is the usage of EDIT_MERGEMSG and EDIT_MSG. I am not sure whether both of them are needed or only one of them (and the other …
=> Some changes to the vimrc

ReleaseNotes.md
Fixes git-for-windows/git#1694
Signed-off-by: Orgad Shaneh <orgads@gmail.com>
=> Fix wrong links and a duplicate entry in 2.17.1 release notes

installer/install.iss
This is a solution that I propose for [#1690](https://github.com/git-for-windows/git/issues/1690). I consider it to be a suggestion, as building an installer was beyond me, thus I'm not sure if it would fix the issue.
As far as my comprehension goes, an [EditorSelectionChanged](https://github.com/izdwuut/build-extra/blob/1d9630e321351b5ecd1609a3effd8df34cd948a1/installer/install.iss#L1084) procedure is responsible for toggling the "next" button. I noticed that it gets invoked in at least 2 situations:
- when an user picks a text editor ([an OnChange event](https://github.com/izdwuut/build-extra/blob/1d9630e321351b5ecd1609a3effd8df34cd948a1/installer/install.iss#L1119))
- once the custom page for configuring the default Git editor is initialized (the InitializeWizard procedure. I have just …
=> Fire EditorSelectionChanged on next button click

git-extra/astextplain
Fixed order of command line arguments for pdftotext.
With current order it prints help message to stderr.
=> Fix astextplain for pdf files

make-file-list.sh
As Git for Windows did not ship PCRE documentation before switching to the PCRE2 dependency, there
should be no need too start shipping PCRE2 documentation now.
=> Exclude PCRE2 documentation from releases

git-extra/git-extra.install.in
Because otherwise, we're probably on vim 8.1 or later.
=> git-extra: only edit vim 8.0's defaults file when it exists

git-extra/PKGBUILD
There's a call to `cmp ` in the .install script.
=> diffutils dep for git-extra

installer/install.iss
0. The superfluous text can be observed in the 2.18.0 release: https://github.com/git-for-windows/git/releases/tag/v2.18.0.windows.1 .
1. Install `Git for Windows SDK`.
2. Run `sdk build git-and-installer` to produce an unsigned installer `Git-0-test-64-bit.exe`.
3. The superfluous text can be observed in the unsigned installer.
4. Apply the code patch.
5. Run `sdk build git-and-installer` to re-build the installer.
6. The superfluous text can no longer be observed in the re-built installer.
=> Remove minor, superfluous text from install.iss.

make-file-list.sh
It was reported in https://github.com/git-for-windows/git/issues/1775 that xsltproc does not work due to a missing .dll. Keeping in mind that xsltproc is not at all required for Git to work, let's exclude that executable.
=> Exclude xsltproc.exe from installer/portable Git/etc

git-extra/git-sdk.sh
Without it, chmod fails for files on this mount
=> git-sdk: Mount other SDK with noacl flag

make-file-list.sh
This is a component that we expect does not get much use. Instead of distributing this component with Git for Windows, remove it. Removing this component will reduce the work associated the release process.
Signed-off-by: Jameson Miller <jamill@microsoft.com>
=> Exclude git-archimport from installer/portable Git/etc

installer/install.iss, installer/release.sh
As nice as the speed-ups are, the patches in question are still in flux, and they are not battle-tested at all.
Let's use the scripted commands by default, and offer the new, fast, experimental builtins as options.
This gives us the best of both worlds: users who want the raw speed improvement we got through three Google Summer of Code projects working in parallel can have that, while others who are reluctant to play guinea pig by running only well-tested code can stay on the safe side.
Plus, it gives us a chance of battle-testing those patches :-)
Note: the code added in this PR will only kick in if bundling a Git built including the latest patches of https://github.com/git-for-windows/git/pull/1800.
=> installer: offer the builtin stash/rebase as experimental options

installer/install.iss
This fixes the issue/feature request mentioned in git-for-windows/git#1872.
As suggested by @PhilipOakley , I have added an extra note to make it more clear what the Vim option actually does.
Signed-off-by: aakriti-jain <aakritijain1102@gmail.com>
=> Make default editor message clear

make-file-list.sh
It is rather small, and comes in handy for scripts
=> Add perl JSON module

make-file-list.sh
Sadly, this fails to build an installer:
```
[...]
Generating file list to be included in the installer ...
error: package 'perl-JSON' not found
```
Reverts git-for-windows/build-extra#209
=> Revert "Add perl JSON module"

portable/release.sh
added script to unset `pack.packSizeLimit` in portableGit64.
this closes issue https://github.com/git-for-windows/git/issues/1903
=> portable/release.sh: unset `pack.packSizeLimit`

ReleaseNotes.md, installer/install.iss, msi/release.sh
We talked about this recently, and I think it is time. There is one particular issue with CMD that opens a particular attack vector that is unavailable for Git Bash and Powershell users: when calling `git log` in a directory in which there is a `git.exe`, that executable is used, no matter how you configure `PATH` or CMD. So if some creative user talks another user into cloning a repository with `git.exe` in the top-level directory, and that other user is unsuspecting of this behavior, they might be talked into calling `git log` and actually run untrusted code.
To raise awareness of this issue, and at the same time to diminish chances of such social-engineering attacks, let's deprecate Git CMD.
Note: this behavior is neither new, nor limited to Git. It just so happens that we can at least …
=> Deprecate Git CMD

please.sh
when packages (like 'Git Credential Manager') are upgraded twice (or
more times) between Git for Windows releases, duplicate entries are
created in 'ReleaseNotes.md'.
Subcommand `mention` writes/edits the 'ReleaseNotes.md'.
Added script to delete every match for 'Comes with [<package> v' before
appending new entry 'Comes with [<package> <version>](<url>)'.
this closes issue https://github.com/git-for-windows/git/issues/1898
=> please.sh: script to fix duplicate relnote entry

installer/install.iss
Clarifies the Command Prompt is an own name, and qualifying it with Windows, i.e. Windows Command Prompt, is redundant. Similarly, full name of PowerShell on Windows is Windows PowerShell.
Mention the Windows PowerShell in the 2nd choice description for even more clarity.
- Follow-up to the ML thread [Git for Windows v2.20.0-rc0](https://groups.google.com/forum/#!msg/git-for-windows/SFqyASXbGxE/v1nSwrOhCQAJ), where I argued use of the "Windows Command Prompt" in
> That setting "Use Git from the Windows Command Prompt" affected PowerShell
> already: by "Windows Command Prompt", I refer to both CMD and PowerShell:
> both are Windows Command Prompts.
is confusing, since
> Shortly, there are two native command prompts in Windows with distinct names:
> - Command Prompt
> - Windows PowerShell …
=> Use the Command Prompt as own name

ReleaseNotes.md
Some people may be confused about the meaning of deprecation
of "Git CMD". Rewording the release notes to call out that:
- using _Command Prompt (cmd.exe)_ is deprecated,
- the _Git CMD_ start menu shortcut (which configures a cmd.exe
instance) is really the same as a vanilla cmd.exe instance.
Signed-off-by: Matthew John Cheetham <mjcheetham@outlook.com>
=> Update 2.19.1 release notes for clearer cmd.exe deprecation

git-extra/notepad
Wrapping lines with fmt could cause comments in COMMIT_EDITMSG to turn into a
comment line and one or more non-comment lines. Wrapping just the comments with
the -p option before wrapping the other lines prevents this from happening.
This fixes git-for-windows/git#1967
I've marked this as "don't merge yet", because I haven't tested it yet. Will update this PR soon.
=> notepad: don't break comments in COMMIT_EDITMSG

portable/release.sh
The argument --no-needs-console prevents the git-bash.exe to run the script at the end of the extraction process. Moreover, the --hide argument is ineffective in hiding the console windows.
This fixes git-for-windows/git#1896
=> Restore post-install script execution for portable installer

ReleaseNotes.md
Inform users that Windows Explorer double counts file sizes for
hard links.
fixes: #1977 (https://github.com/git-for-windows/git/issues/1997)
Signed-off-by: Philip Oakley <philipoakley@iee.org>
---
I haven't tested this with a full build and install yet, but it looked simple enough, apart from a minor concern about the '#' in the updated markdown text.
A friendly reminder for new contributors:
DCO stands for [Developer's Certificate of Origin](https://github.com/git/git/blob/v2.18.0/Documentation/SubmittingPatches#L304-L349).
We require all commits to be DCO signed-off in case we need to track down and handle legal and/or technical issues.
To DCO sign-off your commits, you could run the `git-commit` command with [the `-s` option](https://git-scm.com/docs/git-commit#git-commit--s) or just …
=> ReleaseNotes: duplicated files are hard links

installer/install.iss
Tell existing users that the now current default is the recommended
choice.
Also tone down slightly the Git from Bash only option text to avoid
a clash of the 'safe/safest' words, and reflow the text.
Signed-off-by: Philip Oakley <philipoakley@iee.org>
Now tested.
=> InstallerPath: recommend the safe integrated path

git-extra/git-sdk.sh
This fixes
https://github.com/git-for-windows/git-for-windows.github.io/pull/18#discussion_r261622367
`fatal: ref HEAD is not a symbolic ref`
Signed-off-by: Philip Oakley <philipoakley@iee.org>
=> git-sdk: silence warning when on detached head

make-file-list.sh
Update the excluded file patterns, so the contents of "/usr/share/awk" will be present in the installer and portable builds. This does not significantly impact the size of the installer, with the full contents of the directory being approximately 50 KB in size.
This fixes git-for-windows/git#1972.
=> Enable support for gawk in-place editing

installer/install.iss
As reported by @JJClements, the File version and Product version of the installer and installed binary were not the same. They are set by the `installer/release.sh` and by using `sdk build (installer | git-and-installer)` commands, which created this discrepancy.
Closes: git-for-windows/git#1797
=> installer: Fix version of installer and installed file

sdk-installer/release.sh, sdk-installer/setup-git-sdk.bat
It was reported in https://github.com/git-for-windows/git-sdk-64/issues/6 that installing into a directory whose path contains a space does not work.
While at it, I had to fix the problem where `.dll` files required by `git-remote-https.exe` were not picked up if they existed in `libexec/git-core/`, and I also activated the FSCache for the checkout.
=> Fix the SDK installer so it respects target directories with spaces in their path

git-extra/git-sdk.sh
With this change, a developer can do this:
```sh
sdk cd msys2-runtime # (with tab-completion now!)
<modify the source files>
sdk build msys2-runtime
```
to build `msys0.dll` (which really is a `msys-2.0.dll`, with a safe name to avoid interfering with the currently-used `msys-2.0.dll`) with local modifications.
=> Support the `msys2-runtime` better in the `sdk` function

git-extra/git-sdk.sh, git-extra/sdk.completion
One of the central missions of Git for Windows' SDK is to make it as easy as humanly possible for Git for Windows users to work on their own feature requests. Yes, it is a complex system, but that does not mean that everybody who wants to contribute as little as an enhanced description of an installer options needs to understand all that.
With this change, we can start to recommend to users to "just download the SDK and then call `sdk edit install.iss` followed by `sdk build installer`".
This PR also brings a couple of other touch-ups to the `sdk` function, more or less because I either needed them to develop this PR (such as `sdk reload --experimental` and `sdk edit git-sdk.sh`) or because I just saw those issues nearby and thought I'd just quickly fix them.
=> Make it a lot easier to start hacking on the installer

git-extra/git-update-git-for-windows
In particular, write the Github error response to stdout if we exceed
the rate limit.
See also https://developer.github.com/v3/#rate-limiting.
Closes https://github.com/git-for-windows/git/issues/1813.
Signed-off-by: Clemens Buchacher <drizzd@gmx.net>
=> handle Github error response

git-extra/git-update-git-for-windows
The Github API has a per-user rate limit. For anonymous users, which we
are, the limit counts per IP address. For large organizations this can
be an issue. Instead, make the latest version check against
gitforwindows.org.
We still make calls to the Github API when we decide that we should
download a new release. But this happens only once per user and Git
release.
Signed-off-by: Clemens Buchacher <drizzd@gmx.net>
See also https://github.com/git-for-windows/git/issues/1813.
=> avoid Github API rate limit

git-extra/PKGBUILD, git-extra/update-via-pacman.bat, make-file-list.sh
This PR adds the Batch file `update-via-pacman.bat` to the top-level directory of any Git for Windows SDK. This script will make it easier, hopefully, to update a local copy of the SDK.
cc @SteveALee
=> git-extra: offer an easy way to update an SDK via Pacman

git-extra/Makefile, git-extra/PKGBUILD, git-extra/git-credential-helper-selector.c, git-extra/git-credential-helper-selector.manifest, git-extra/git-credential-helper-selector.rc
The idea is to have a credential helper that discovers all other credential helpers on the `PATH` and lets the user choose one (or none).
This meta helper will come in handy to avoid surprises where users run a portable Git on someone else's computer and expect no credentials to be stored there.
This addresses https://github.com/git-for-windows/git/issues/2116.
=> Add a meta credential helper

installer/install.iss
git-for-windows/git issue #2018 suggests ssh.variant should be set if the user selects plink for ssh.  This change expands on that requirement.  
- adds some text to indicate ssh.variant will be set
- adds a checkbox to select if tortoise plink is being used.  This affects the command parameters when running plink
- sets ssh.variant to putty or tortoiseshell if needed
- unset ssh.variant if it was set in a previous install
- track previous selection of the checkbox
Installer git configuration settings are not always removed during uninstall and this update does not change current behavior.
=> Set ssh.variant for plink or tortoise plink

installer/install.iss, installer/release.sh, nuget/GitForWindows.nuspec.in, nuget/release.sh, portable/release.sh
A minimal fix for git-for-windows/git#2291.
Note no change in mingit because that is just git.exe, and the missing /dev directory is only a problem for bash.exe.
Built and validated the regular installer, NuGet package and portable installers.
=> Add dev directory during setup

installer/install.iss
Why: Third-party applications or IT tools must be able to know
if the latest Git version is installed on the system
by means of version number comparisons.
How: Remove platform identifier from the Product Version.
Product Version now displays x.x.x.x instead of x.x.x.windows.x
See https://github.com/git-for-windows/git/issues/2223
Signed-off-by: Audric Guerin <49029709+AudricGuerin@users.noreply.github.com>
=> fix installer's Product Version inconsistency with older versions

installer/install.iss
This update is a part fix for #https://github.com/git-for-windows/git/issues/2349 where users who haven't followed or noticed the recommendation probably won't be able to build the Git Visual Studio version in vs/master because the don't have Git on their CMD window path.
=> path choice: highlight the recommended choice in <RED>

git-extra/git-sdk.sh
The recommended way in the Git for Windows SDK to start developing patches for any package is to run something like this:
```sh
sdk cd <package-name>
sdk build
```
However, this is not as easy to use as it should: after editing any source file, it would complain about checksum mismatches (which is correct, but not helpful). For other packages, it will complain that it does not find the GPG key with which the upstream sources were signed.
Let's make all of this much more fun by skipping those checks. The checksums will be updated anyway, as part of the semi-automated process to build and upload the package to Git for Windows' Pacman repository. Not anything a contributor should need to worry about.
=> Make `sdk build` less cumbersome to use

git-extra/git-sdk.sh
In order to simplify changes similar to 5bbd68e ("sdk build: do not
verify checksums nor GPG keys", 2019-10-09), move the common makepkg
options into a variable.
=> git-sdk: don't repeat the common makepkg options

.gitignore, ReleaseNotes.md, git-extra/git-extra.install.in, installer/install.iss, installer/release.sh, make-file-list.sh, mingit/release.sh, mingw-w64-git-lfs/git-lfs.install, portable/release.sh
This is a follow-up PR for https://github.com/git-for-windows/git/pull/2358, and it will need to be merged _before_ that one, so that the next snapshot won't be broken.
The idea is to prepare the scripts that generate the Git for Windows installer, the Portable Git and the MinGit versions to accommodate for Git versions that have only one system config: Instead of reading `C:\ProgramData\Git\config` and then `C:\Program Files\Git\mingw64\etc\gitconfig` (or for 32-bit Git on 64-bit Windows, `C:\Program Files (x86)\Git\mingw32\etc\gitconfig`), we now only read from the quite intuitive location `C:\Program Files\Git\etc\gitconfig`, i.e. without the `mingw64` part.
This also addresses the issue raised many times that the Portable Git relied on settings configured _outside_ of the Portable Git …
=> Update installer/portable/mingit for the new system config location

installer/install.iss, installer/release.sh
There is a pretty old bug where the Git for Windows installer warns about a "downgrade" when upgrading from, say, v2.23.0-rc2 to v2.23.0, because the versions that are actually compared are of the format `N.N.N.N` (by stripping out non-numerical letters, in the example, the compared versions would be `2.23.0.2` vs `2.23.0.0`).
Let's fix this by trying to be a bit more careful when we're about to warn about a downgrade, and compare the output of the installed `git version` vs the one we're about to install.
=> Installer: stop complaining about "downgrading" when upgrading from an rc version

installer/install.iss
This fixes https://github.com/git-for-windows/git/issues/2388.
=> Teach the installer to create Cygwin symlinks even in non-US locales

git-extra/getgit
**Handle patch number** 
While there's a patch number greater than 1 appended, the name of the file about to be downloaded should also have that number appended after the version part.   
For example: `v2.24.0.windows.2` ==> `PortableGit-2.24.0.2-64-bit.7z.exe`
**Remove the inadvertently added "-n" option**
In an updating scenario, this "-n" option in the `update` function would prevent files from being overwritten, yet our intention indeed is to overwrite them.
**Move the backed up files to /tmp instead of "rm -rf" them**
This can help to keep the original files at least in the temporary folder in case something unexpected happen. Users can restore the original files as they wish.
**Let `Git Bash Here` perform an identical behavior on Cygwin comparing to Git-for-windows**
To let `Git …
=> Handle patch number and some other improvements and fixes

git-extra/git-extra.install.in, git-extra/gitconfig, mingit/release.sh
I made a mistake when I added those `include.path` settings to MinGit's system config which are intended to inherit the installed Git for Windows' defaults: these includes are added _to the beginning_, which means that MinGit's hard-coded `core.autocrlf` and friends always override Git for Windows' defaults. Which defeats the purpose.
Let's fix that, and while at it also remove the no longer needed `http.sslCAInfo` from the system gitconfig of Git for Windows' SDK (the installer will _still_ set it, to help Git LFS use Git for Windows' certificate bundle).
=> Various system gitconfig-related fixes, in particular for MinGit

git-extra/git-update-git-for-windows
The `git update-git-for-windows` script tries to be smart and only show the Toast in Windows 8 and later. But the test was broken by an update to Cygwin v3.x, which changed the format of the output of `uname -s`.
This fixes that.
=> Show the update message in the Action Center again

git-extra/git-sdk.sh
Inspired by a couple recent user reports that `sdk cd installer` did not work (because it failed to initialize the `/usr/src/build-extra/` worktree), I went ahead and fixed that, and while at it, also fixed another pet peeve of mine: when running `sdk build` in, say, `mingw-w64-git`, the build was neither parallel nor restricted to the 64-bit build.
This PR addresses those issues.
=> Assorted fixes for the `sdk` function

installer/install.iss, installer/release.sh
When upgrading Git-for-Windows, the current default behavior is to go through the entire installation dialog, which shows a number of pages for setting options.  This change suppresses those pages during upgrade, using the previous values (or values specified on the command installer command line, if they are present).  It does so by checking, for each options page, whether all the values on it have previously-set values.  
Behavior on two edge cases:
If a new option page is added, it's values won't be previously set, so it will be shown, even on upgrade.
If the user uninstalls and then reinstalls Git for Windows, all the pages/options are shown.
One known flaw: when all pages are shown, the last page before installation has a button labeled 'Install' instead of 'Next'.  With this change, …
=> skip options pages when upgrading

portable/release.sh
Enable `core.fscache` in the portable git by default as discussed at
[#2467](https://github.com/git-for-windows/git/issues/2467#issuecomment-574109742).
=> Enable FSCache in the Portable Git by default

git-extra/git-update-git-for-windows
Implementation as suggested by @dscho in https://github.com/git-for-windows/git/issues/2485#issuecomment-576653219
Depends on `set_recently_seen` being called to make transision, up to user to rm exising global config which is ignored going forward.
Personally I'd rather store it somewhere outside of $HOME, like `/tmp` (problematic for per-user installs I'd guess), `~/.cache/gitforwindows` or even the registry. Any suggestions?
=> Cache recentlySeenVersion in ~/.git-for-windows-updater instead of global config

installer/install.iss, msi/release.sh
The reason to deprecate Git CMD went away as of https://github.com/git-for-windows/MINGW-packages/commit/82172388b. So let's revert the deprecation.
=> Un-deprecate Git CMD

git-extra/git-extra.install, git-extra/git-extra.install.in
The installer bash script comments out a part of Vim's defaults.vim
file. This part resets the cursor line to the last one when reopening a
file. This is not desired in the case of commit messages, which are
always the same file name but composed from scratch each time.
In the meantime, MSYS2 Vim was updated to 8.2.
This causes a warning on installing git-extra because the installer
script unconditionally greps a Vim 8.1 file that is no longer present.
Fix this by checking the file's presence.
A similar installer script section is not necessary for Vim 8.2, because
this version includes in this line-resetting automatism an exception for
all file types matching "*commit*".
A friendly reminder for new contributors:
DCO stands for [Developer's Certificate of …
=> installer: handle Vim 8.2

installer/install.iss
and minor change in the text to VisualStudioCode to distinguish its MIT-licensed "core" with the provided un-free binaries (+telemetry/tracking) between the option added.
As the reference was not 100% clean - this fixes https://github.com/git-for-windows/git/issues/2537.
=> Fix #2537 add VSCodium

git-extra/git-update-git-for-windows
Relates to issue [#2584](https://github.com/git-for-windows/git/issues/2548#issue-583892831).  This PR should stop the new installer showing a initial install screen by using the existing installer /VERYSILENT command.  
As I was using Visual Studio to make these changes an update to the .gitignore got included to avoid additional visual studio specific settings being included in the repo, I've left the .gitignore change in because I didn't think it would harm anything but can remove if required.  
This is my first contribution to git so I've not managed to build and test the code however considering the minor changes I didn't know if this was required.  I'll try and have a got at building the updated installer over the weekend.  
Please let me know if there are any other changes that are …
=> Updated Update Install Command to improve silent installation

installer/install.iss, render-release-notes.sh
Improve the accessibility and readability of the release notes.
1. Add a start menu icon for the GfW's own release notes, so use can find and read them.
2. Small improvement to the readability of the notes by using larger, open 'white' triangles for the collapsible regions of the release notes - feels more like the typical explorer look. Previously they looked like basic bullet points
3. Also, specifically mark the upstream Git's link as being for their release notes (not tested successfully - may not have invoked the please.sh appropriately. I'd expected the `sdk build installer` to do it's magic - guidance needed!)
=> Provide GfW ReleaseNote Start menu Icon, and tweak collapsible div marker 

installer/install.iss
---
Note that the icons are listed in alphabetic order on W10 start menu (on my machine), so we have:
Bash, CMD, FAQs, GUI, Release Notes.
=> Add Git FAQ icon to start menu linking to the wiki/FAQ

ReleaseNotes.md, installer/install.iss, installer/release.sh, msi/release.sh
The main two things in this PR: we now offer an experimental option to opt-in to the pseudo console support, and we silence the `pull.rebase` warning proactively by forcing the user to choose in the installer.
While at it, I also slipped in a change accommodating for https://github.com/git-for-windows/MINGW-packages/pull/40: the `edit-git-bash.exe` helper is now included in the `mingw-w64-git` package (originally I had planned to modify the `git-bash.exe` via `edit-git-bash` so that it would enable pseudo consoles, but that would be confusing, as it would affect _only_ `git-bash.exe` (and not, say, `/cmd/git.exe -c alias.mintty='!mintty' mintty`).
=> Address the fallout from the upgrade to MSYS2 runtime v3.1.4

installer/install.iss
Change `fast-forard` to `fast-forward`.
```
Signed-off-by: Shane Grüling <shane.grueling@portalwelten.de>
```
This fixes https://github.com/git-for-windows/git/issues/2652
=> Fix typo in the installer

installer/install.iss
We currently don't save the `fast-forward only` pull behaviour correctly.
Let's fix that.
This fixes git-for-windows/git#2668
=> Pull option fix

installer/install.iss
The Pseudo Console support experimental option was not being recalled
correctly on subsequent installs. If the option was unset it would
default to unchecked (correct), but if the option was set to 'disabled'
then it would become default checked!
Signed-off-by: Matthew John Cheetham <mjcheetham@outlook.com>
=> Fix recall of experimental pseudo console support setting

.gitignore, get-sources.sh, git-extra/git-sdk.sh, installer/install.iss, make-file-list.sh, mingw-w64-git-credential-manager-core/PKGBUILD, please.sh
Add Git Credential Manager (GCM) Core to the Git for Windows installer.
GCM Core is the cross-platform credential helper that will eventually
replace the exiting GCM for Windows (and GCM for Mac/Linux) helpers.
Move the "Enable Git Credential Manager" option to its own, new page
where you can select between the three options: none, GCM, or GCM Core.
Reusing the same "Use Credential Manager" replay choice key, we can
ensure that existing choices for GCM for Windows are carried forwards to
the new three-option choice. Enabled = GCM for Windows, Disabled = None,
and a new option Core = GCM Core.
Because GCM Core is still in beta we do not make it the default yet; GCM
for Windows is the default.
Signed-off-by: Matthew John Cheetham <mjcheetham@outlook.com>
=> Add support for Git Credential Manager Core as a credential helper option

git-extra/git-sdk.sh
We used to hard-code the default Desktop path, but that can be overridden (and often is, e.g. when the user follows OneDrive's suggestion to back up the Desktop folder on OneDrive).
This fixes https://github.com/git-for-windows/git-sdk-64/issues/22
=> sdk create-desktop-icon: use correct path to Desktop

installer/install.iss
We've dropped support for Windows versions older than Windows Vista
years ago. There's no reason to keep these special code paths  in the
installer just to work around missing features in these old versions.
Since we error out early on old Windows versions, this code was unreachable.
=> Installer: drop special treatment for Windows versions prior to Vista

installer/install.iss
As noted by @satsuper in https://github.com/git-for-windows/git/issues/2729#issuecomment-653090026, when a user enabled support for Pseudo Consoles and then reinstalled to disable it, by mistake the Pseudo Console support would _still_ be enabled.
The reason? We only write `/etc/git-bash.config` to enable the Pseudo Console support, but not when we disable it (because it is disabled by default, anyway). However, we failed to remove that file upon uninstall/upgrade.
=> installer: allow Pseudo Console support to be re-disabled

git-extra/git-credential-helper-selector.c
Apparently with the upgrade to mingw-w64's GCC v10.x, we have to be a bit more strict with our use of the string format specifier (`%s` will render UTF-8 strings, even when specified e.g. in an `swprintf()` format, we need to use `%S` for wide Unicode strings).
This fixes https://github.com/git-for-windows/git/issues/2776
While at it, we now support toggling the checkbox via keyboard (<kbd>Alt</kbd>+<kbd>A</kbd>).
=> Fix persisting the choice in the credential helper selector

ReleaseNotes.md
Closes git-for-windows/git#2785
=> Added known issue about command hints for non-POSIX shells.

installer/install.iss
We're currently assuming that directly called editors ignore our request
to hide their initial window, but some editors honor that request.
This causes the installer to get stuck waiting for user input in a
hidden window.
This fixes git-for-windows/git#2684.
=> installer: only use SW_HIDE on custom editors that use a wrapper script

installer/install.iss
Since v2.28.0, Git supports `init.defaultBranch` as a way to specify what branch name to use when initializing new repositories. Git for Windows does not have any UI to present that choice to the user. This PR changes that.
Running `./installer/release.sh -d DefaultBranch` in a local check out shows how the page looks like:
=> installer: offer to configure `init.defaultBranch`

check-for-missing-dlls.sh, make-file-list.sh
A recent snapshot was missing `libzstd.dll` although it was required to load `libcurl-4.dll`. With this script, which I intend to hook up in an automated build, we should be able to safeguard against similar issues in the future.
While at it, clean up the exclusion patterns in `make-file-list.sh` a bit more.
=> Prevent missing DLLs in Git for Windows

check-for-missing-dlls.sh, make-file-list.sh
This PR enhances the script we recently introduced to verify that we're not missing any `.dll` files, to _also_ verify that we're not shipping superfluous `.dll` files either.
=> Exclude unneeded DLLs from the installer/MinGit

installer/install.iss
I completely missed the fact that we still install GCM(W) by default... 😠
=> installer: default to GCM Core (including fresh installs, not just upgrades)

installer/install.iss
This (hopefully) addresses https://github.com/git-for-windows/git/issues/2384.
=> installer: when spawning `cmd`, disable `AutoRun`

check-for-missing-dlls.sh, make-file-list.sh
We recently stumbled over a breakage in the 32-bit Git for Windows SDK, where GNU Privacy Guard was completely broken due to a missing `.dll` (caused by a `libnettle` upgrade).
Let's modify the script we already use to prevent such issues from happening in the 64-bit Git for Windows SDK without being noticed, so that it extends to 32-bit as well.
=> Adapt `check-for-missing-dlls.sh` for i686

installer/install.iss
Yesterday, after I had released Git for Windows v2.29.0-rc2, I realized that I had been asked to choose whether I want to override the default branch name, even if I had checked the "Only show new options" checkbox, and even if I had previously said that I want to stay with Git's default.
Turns out that this choice was not recorded at all, due to an under-documented feature of the `SetPreviousData(Key,Value)` function: when specifying the empty string as value, it is not recorded at all; Instead, any previously recorded data for that key is deleted.
While working around this feature, I also noticed how easy it is to specify an invalid branch name, so I added code to prevent that from being accepted.
=> installer: two fixes regarding the default branch name choice

render-release-notes.sh
Third version, based on most recent master.
Opinions, especially the colours! 
(Helped by colleague @strath.ac.uk who knows a bit more about some of the HTML fu)
Also, should a title at the bottom of the page auto scroll a little when opened, to show something happening..
P.
The Git for Windows Release Notes show the "Changes Since" title lines
but don't tell the user the current version they refer to.
Convert the Arrow indication to a floating button at the top left
of the header showing the version, and an expansion arrow.
Currently the button is a default grey shade, with a contrasting
green font lettering (valuely matching the logo's green).
---
RFC. The previous white font is not readable/accessible against
the grey button.
=> [RFC] ReleaseNotes: Show 'current' version for "Changes Since" titles

git-extra/git-credential-helper-selector.c
In git-for-windows/git@6d8684161ee9, we fixed a bug where it would quote command-line arguments with trailing backslashes incorrectly when they needed to be quoted.
While the helper-selector only quotes paths to files (which, by definition, cannot end in a backslash), we still should fix the
`quote()` function, just in case that we will want to use it on parameters other than file paths.
=> helper-selector: fix quoting of trailing backslashes

git-extra/git-update-git-for-windows
When installer is being executed MSYS2 subsystem tries to convert unix paths to Windows paths.
It seems it applies to installer arguments as well (because they start with slash).
Thus `/SILENT` is converted to `C:/Program Files/Git/SILENT` (or something alike).
This effectively bypasses installer arguments.
The solution is to escape slashes in installer arguments.
Signed-off-by: ge0rdi <ge0rdi@users.noreply.github.com>
---
With this change git update works silently without any user interaction and any progress.
That second part (no progress displayed) is caused by `/VERYSILENT` option and imo it is not good. Because user doesn't even know if the installation started/ended.
Personally I think `/VERYSILENT` should be removed. Without that option it seems to work well for me. There is still …
=> git update-git-for-windows: escape installer arguments

git-extra/git-credential-helper-selector.c
In a conversation with @mjcheetham I realized that neither `%s` nor `%S` are appropriate format specifiers for wide-character string arguments in `printf()`/`wprintf()` calls. Instead, `%ls` is the best option.
After fixing this, I noticed in my tests that the helper selector constructed a command line with improperly quoted paths. That's the other fix included in this PR.
=> A couple fixes for the credential helper selector

git-extra/git-extra.install.in
This teaches `/etc/profile` to handle the special value `MSYSTEM=ARM64` to set up the environment such that `PATH` prefers executables in `/arm64/bin/` but also falls back to `/mingw32/bin/`.
The basis is still an i686 version of MSYS2: there is currently no toolchain support in MSYS2 to build executables targeting Windows/ARM64, but there is a built-in i686 emulator in WIndows/ARM64.
=> Start support for MSYSTEM=ARM64

please.sh, portable/release.sh
Builds further on https://github.com/git-for-windows/build-extra/pull/321. Very much a proof of concept, just sharing here for inspiration.
**Example release based on this PR**: https://github.com/dennisameling/git/releases/tag/2.30.0-beta2
Results in an actual working portable installer for ARM64 when taking the following steps:
- `sdk build mingw-w64-git`
- `pacman -U mingw-w64-i686-git-2.30.0.2.f8cbc844b8-1-any.pkg.tar.xz` (replace the filename with the actual filename that's generated)
- `sdk build git-extra` (so that `/etc/profile` gets overwritten to include ARM64)
- `pacman -U git-extra-1.1.513.20ab9a5-1-i686.pkg.tar.xz` (replace the filename with the actual filename that's generated)
- ([create the arm64 binaries](https://github.com/git-for-windows/git/pull/2915#issuecomment-739538 …
=> portable: add arm64 artifact option

mingit/release.sh
Related to https://github.com/git-for-windows/build-extra/pull/323, needs https://github.com/git-for-windows/build-extra/pull/321 & #323 
Example release based on this PR: https://github.com/dennisameling/git/releases/tag/2.30.0-beta2
This probably needs optimization. The generated ZIP is 207MB 😅 any tips/guidance are/is welcome!
The mingit packages are used by [desktop/dugite-native](https://github.com/desktop/dugite-native) > [desktop/dugite](https://github.com/desktop/dugite) > [desktop/desktop](https://github.com/desktop/desktop) (GitHub Desktop), so I tested with those as well.
⚠️ Note: `dugite-native` is still on Git 2.26.2, so the failing tests might be due to the bump to 2.30.0 as well
dugite-native: https://github.com/desktop/dugite-native/pull/347
dugite: …
=> mingit: add arm64 artifact option

archive/release.sh
Needs https://github.com/git-for-windows/build-extra/pull/323
Adds an --include-arm64-artifacts argument to the archive script, just like for portable (#323) and mingit (#324)
=> archive: add arm64 artifact option

git-extra/create-shortcut.c, git-extra/git-sdk.sh
Given OneDrive with the Desktop Redirection feature, and other supported methods to NOT have your Desktop in %USERPROFILE%\Desktop, we should use a more sophisticated method to get the path to the Desktop in order to put a shortcut there. Since we are using Bash we need to step out and invoke a vbs script to get the SpecialFolder called Desktop, and use that as a path.
=> Let `sdk create-desktop-icon` use the correct API to determine the Desktop's location

installer/install.iss, installer/release.sh
Adds ARM64 support to the installer 🚀 
Currently installs ARM64 Git into `C:\Program Files (x86)\Git` by default.
=> installer: add arm64 artifact option

.vscode/settings.json, pacman-helper.sh
Git for Windows' Pacman package databases are updated only via automated builds. In at least one of them, bogus entries were added (see git-for-windows/git#3034 and git-for-windows/git#3035). This PR adjusts the automated builds so that that won't happen again (or at least so that it will self-heal).
=> Sanitize Pacman databases while adding new packages

installer/install.iss, installer/release.sh
In silent mode, we do not see the "Processes" page to which the error message refers:
Let's change the error message in silent mode, to be more helpful. Example:
An alternative I would have _loved_ to implement would have shown the wizard form via `WizardForm.Show()`, i.e. by turning the silent installer non-silent. However, clicking the <kbd>OK</kbd> button of the error message will cause the installer to exit anyway, i.e. it won't let the user interact with the wizard form before exiting, so that is not an option.
This fixes https://github.com/git-for-windows/git/issues/3118
=> Improve error message in silent mode when Git for Windows' files are in use

installer/install.iss
This fixes the issue reported in [git-for-windows#3155](https://github.com/git-for-windows/git/issues/3155) as suggested by @dscho.
=> Use ShellExecAsOriginalUser() instead of ShellExec() for custom editor tests

installer/install.iss
It was reported in https://github.com/git-for-windows/git/issues/3161 that the Git installer will throw errors when the previous Git installation was deleted manually.
Let's work around this by simply pretending that the system config was empty.
=> installer: ignore when the previous Git installation was deleted

installer/install.iss
There is no reason why the installer should not only create the `HKCU\Console\Git Bash` and `HKCU\Console\Git CMD` keys, but also modify the `HKCU\Console` key.
It needlessly overwrites user settings and is redundant because of the Git-specific keys.
Signed-off-by: Adrian Georg Herrmann <adrian.ghc@outlook.com>
=> Don't modify HKCU\Console root key

installer/install.iss
Builds further on https://github.com/git-for-windows/build-extra/pull/330
The Git for Windows ARM64 installation ideally should be installed in the 64-bit Program Files folder. Inno Setup 6.0 added support for 64-bit on Windows ARM64. This commit leverages this support.
The installation directory is correctly set to `C:\Program Files\Git`:
The Git Credential Manager radio buttons are enabled correctly in the 64-bit ARM64 installer:
=> installer: add 64-bit support for ARM64

git-extra/inputrc
This PR removes one unused and incorrect keybinding from `/etc/inputrc`.
To see the problem, for example, you can press <kbd>Ctrl-x</kbd><kbd>Ctrl-r</kbd> in a Bash session. <kbd>Ctrl-x</kbd><kbd>Ctrl-r</kbd> reloads the keybindings defined in `~/.inputrc`. After that, <kd>Backspace</kbd> will not work as expected in the Bash session; it removes the entire line before the cursor position.
This is caused by the following incorrect keybinding in `/etc/inputrc`:
```inputrc
"\C-?": backward-kill-line        # Ctrl-BackSpace
```
Here, `"\C-?"` is not usually <kbd>Ctrl-BackSpace</kbd> but <kbd>Backspace</kbd>. The reason why we don't see this behavior initially (before pressing <kbd>Ctrl-x</kbd><kbd>Ctrl-r</kbd>) is that it is overwritten by another keybinding set up by Bash/Readline in the …
=> git-extra (inputrc): remove an unused and incorrect keybinding

installer/install.iss
Provides initial support for installing basic Git Bash fragments for Windows Terminal (see git-for-windows/git/issues/3183 for details).
Known Issues:
- Final location of git-bash-global.json and git-bash-local.json in installer repository TBD
- Mix and match of globally installed Terminal and locally installed Git (Bash) and vice versa does not work
- Custom Git installation directories are not supported in the fragments
- Should probably include a pre-generated UUIDv5 according to the [Terminal docs](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions#how-to-determine-the-guid-of-an-existing-profile) for later modification
I am raising this WIP pull request to initiate the discussion on how to fix the aforementioned issues.
=> installer: provide Windows Terminal Fragment Extension

git-extra/git-update-git-for-windows
For the upcoming ARM64 support, as well as for the Microsoft fork of Git for Windows, it would be helpful if there was a way to update from the GitHub Releases of the respective fork instead of Git for Windows' own fork. This PR makes that easy.T o ask the updater to look for new versions at, say, https://github.com/dennisameling/git/releases, run the following command
as administrator:
git config \
-f "$(git --exec-path)/git-update-git-for-windows.config" \
update.fromFork dennisameling/git
Cc: @dennisameling
=> git update-git-for-windows: optionally update from a fork

git-extra/git-update-git-for-windows
Builds further on #338 
Needed for https://github.com/git-for-windows/git/issues/3107
If the `/arm64/bin` folder is present, we assume that the user has the ARM64 version of Git for Windows installed. When a new version is available, we'll then automatically download the ARM64 version. This is similar to the logic in [git-wrapper.c](https://github.com/git-for-windows/MINGW-packages/blob/a723a9beca720c36378bce90e2085e0828d90012/mingw-w64-git/git-wrapper.c#L139-L144) in mingw-w64-git.
Sample release with a fake ARM64 installer (renamed 64-bit installer, just to show that the installer indeed downloads the correct file): https://github.com/dennisameling/git/releases/tag/2.31.2.windows.1
Tested as follows:
1. Ensure `/arm64/bin` folder is present
2. Point the update check script to my fake …
=> git update-git-for-windows: download ARM64 Git for Windows if applicable

git-extra/git-update-git-for-windows
I recently installed v2.32.0-rc0 and the auto-updater suggested to "upgrade" to v2.31.1. This fixes that.
=> Fix auto-updater when an -rc0 version is installed

installer/install.iss
Using /usr/bin/bash does not fully initialise the environment, see https://github.com/git-for-windows/build-extra/pull/339#discussion_r634803606 for details
Signed-off-by: Paul "TBBle" Hampson <Paul.Hampson@Pobox.com>
=> Use /bin/bash when launching from Windows Terminal

installer/install.iss, installer/release.sh
When upgrading from prior versions, the Components page was not shown by default (because the installer thinks that there were no options that had not been shown during earlier installations/upgrades).
Let's fix this.
Cc: @Okeanos
=> installer: make the Windows Terminal profile option more visible

installer/install.iss, installer/release.sh
It has been simmering in Git for Windows for a full release cycle, now it is time to give it even wider exposure. This is how the page looks at the moment:
We might want to have a link to a verbose description of the built-in FSMonitor (such as a blog post), but I am not aware of any web page to which we could link. Maybe I'll have to blog about it...
=> installer: offer the built-in FSMonitor explicitly as an option

installer/install.iss
This fixes a long-standing bug that I only detected while trying to release Git for Windows v2.32.0-rc2: if there were unseen experimental options, they would not be shown by mistake, but skipped when "Only show new options" was checked.
=> installer: do show unseen experimental options

installer/helpers.inc.iss, installer/install.iss
We now have long-running Git processes, processes that would potentially block upgrades.
However, due to a mistake the installer would not show them: we only looked for processes using `/mingw64/bin/git.exe` (or the equivalent in 32-bit setups), while the FSMonitor daemon typically runs via `/mingw64/libexec/git-core/git.exe`, namely when it was spawned implicitly.
Since the installer missed these processes, they would not be killed, and InnoSetup would "helpfully" require a reboot after the upgrade.
This PR not only plugs that hole by detecting more Git processes, but also brings code to automatically shut down all FSMonitor daemons before the actual upgrade.
The method presented here might not be ideal, but is probably a bit more robust and simpler than the approach implemented …
=> installer: try to deal with running FSMonitor daemons gracefully

installer/environment.inc.iss, installer/helpers.inc.iss, installer/install.iss, installer/release.sh
Scalar is a project that tests out new strategies to make Git scale better. Over the years, hits like "partial clone" and "commit-graph" and `git maintenance` were developed in Scalar and then upstreamed into Git.
Over in the Microsoft fork, I am busy at work re-implementing the remaining parts of [Scalar](https://github.com/microsoft/scalar#readme) in C, putting them in `contrib/scalar/`. The idea is to eventually upstream all remaining bits and pieces of Scalar that do not require the GVFS protocol (which are only required because Azure Repos do not support partial clones, at time of writing).
To give this a smooth gliding path, I want to include the `contrib/scalar/` parts in the releases of the Microsoft fork first, given them some real world testing, and then start upstreaming.
To …
=> In preparation for supporting contrib/scalar/, teach the installer about it

ReleaseNotes.md, installer/install.iss
Sublime Text has recently been released as version 4. Along with this new
version the install directory has been changed to no longer include the version
number in the directory name. Change the installer to detect newer versions of
Sublime Text and prefer them over version 3.
This fixes git-for-windows/git#3248
=> installer: Support Sublime Text 4 and (probably) newer

ReleaseNotes.md, installer/install.iss
I just posted a "Show and Tell" in Git for Windows' discussions: https://github.com/git-for-windows/git/discussions/3251
A strong motivator for that was to have a place to which I can point interested readers who wish to find out what the FSMonitor business is all about.
So let's point them there, from the release notes, and from Git for Windows' installer.
=> Link to the FSMonitor discussion from the release notes/the installer

installer/install.iss
This allows user-customizations of the profile to continue to refer to the profile even if its name or directory should change.
Based on discussion from https://github.com/microsoft/terminal/issues/10374 and https://github.com/git-for-windows/build-extra/pull/339#issuecomment-857043296
=> provide explicit GUID for Windows Terminal profile

installer/install.iss
The most likely reasons why users have .vfs versions (i.e. Git for Windows flavors whose `git version` show something like `git version 2.31.1.vfs.0.1`) is that they have downloaded VFS for Git or Scalar and cloned from an Azure Repo.
In such a scenario, it would not be good to switch away from a .vfs version because regular Git for Windows has no support to talk the GVFS protocol (which is used by the .vfs flavor to emulate partial clones), and therefore their VFS for Git or Scalar enlistments would be broken as a consequence.
Let's try to be helpful in such circumstances and give the user a chance to stay with the working setup. This is how it will look like:
=> Warn about switching away from .vfs versions

git-extra/git-update-git-for-windows
This is not super-important for `git-for-windows/git` because it always uses `-rcX` text in its pre-releases. However, in `microsoft/git` we use regular-versioned tags as prereleases that we hand to dogfooders before promoting that same tag as a full release. This has led to users being prompted for upgrades because their version doesn't match the latest, even though their current version is newer.
Always use a version comparison that compares the components carefully. I tested the new `version_compare` very carefully, but am not sure of how to test the change in the second commit.
=> Use signed version comparisons before recommending upgrade

git-extra/PKGBUILD
It annoyed me one too many times that `git up<Tab>` would not show the `update-git-for-windows` command. So I fixed it.
=> Enable Tab-completion of `git update-git-for-windows`

installer/install.iss
Under certain circumstances, enlistments registered with Scalar.NET were removed without being unregistered.
Do not try to register them.
=> installer: avoid trying to register missing Scalar enlistments

make-file-list.sh, mingit/release.sh
Together with https://github.com/git-for-windows/MINGW-packages/pull/52, this addresses a couple of concerns raised in https://github.com/git-for-windows/git/issues/1439#issuecomment-865501015 (and subsequent comments on that ticket).
=> Reduce MinGit's size a little

make-file-list.sh
The files in there are used by nano for syntax highlighting
and get included from our `/ec/nanorc`.
This is a partial revert of 43db63670e49f (make-file-list: exclude some unneeded files).
This fixes git-for-windows/git#3315
We might still want to exclude them for MinGit, but not the rest.
=> make-file-list.sh: don't exclude /usr/share/nano

mingw-w64-git-credential-manager-core/PKGBUILD
Stripping assembly signatures out of PE files without adjusting the header information leads to corrupted binaries. That causes issues with our effort to cresate an MSIX package.
=> GCM Core: don't strip signatures

please.sh
Requires PDB `.tar.xz` file placed in `build-extra/cached-source-packages` (same as when executing `please.sh bundle_pdbs`). Verified (with changes in [vdye/git@feature/include-pdbs](https://github.com/vdye/git/tree/feature/include-pdbs)):
- workflow execution: https://github.com/vdye/git/actions/runs/1079007958
- created release (manually published): https://github.com/vdye/git/releases/tag/v2.32.0.vfs.pdb
=> Add `--include-pdbs` option to `make_installers_from_mingw_w64_git()`

installer/install.iss, installer/release.sh
This pull request addresses git-for-windows/git/issues/1683 and git-for-windows/git/issues/2944 by adding an additional detecting mechanism for Windows OpenSSH to the choice page formerly known as PuTTYPage and allows the user to "skip" the installation of the bundled SSH related binaries that Windows also supplies.
When selected this allows interaction between for example KeePassXC OpenSSH agent integration and Git. This may partially address keepassxreboot/keepassxc/issues/4681 I suppose.
There is a small problem with the choice page, though, at the moment because the installer window is not tall enough to fully display the choices.
I suppose rewording the texts or omitting the PuTTY/Plink option if it wasn't successfully detected would work?
Also I have no 32Bit system to test this …
=> Add choice for external OpenSSH

ReleaseNotes.md, installer/install.iss, installer/release.sh
This fixes three problems I just saw while testing a tentative version of the -rc2 installer:
- The running instances of the FSMonitor daemon did not shut down properly because the stop command was invoked from the gitdirs instead of the worktree directories, and FSMonitor now mistakes the former scenario for being called in a bare repository.
- The components page was shown still, to show the Windows Terminal Profile option (which was new in v2.32.0), even if upgrading _from v2.32.0_.
- The "external SSH" choice was not shown when running the installer in the "Only show unseen options" mode, even if it could not possibly have been seen before v2.33.0.
[EDIT] While at it, I also added the missing entry in the release notes where I want to mention that the FSMonitor patches were updated.
=> Some hot fixes for the installer, in preparation for v2.33.0-rc2

make-file-list.sh
When asked to build an installer or a portable with localization,
we should also add the localization for git-gui and gitk.
=> make-file-list: include git-gui and gitk l10n in WITH_L10N

installer/install.iss
As documented in git-for-windows/git/issues/3368 the installer has to check for a valid SSH choice before attempting to remove the bundled SSH binaries.
As @PetSerAl helpfully pointed out in the [original pull request](https://github.com/git-for-windows/build-extra/pull/367#discussion_r693312186) the installer has to verify any SSH choice was made or else things break.
This fixes git-for-windows/git/issues/3368 – I used a [Windows 7 VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), uninstalled the bundled OpenSSH, and ran the newly built installer with this fix applied, confirming @PetSerAl's findings.
=> installer: fix missing check for SSH choice

git-extra/git-sdk.sh
When the environment variable `MSYS_NO_PATHCONV` is set, the MSYS2 runtime will stop trying to convert environment variables and command-line arguments it detects as Unix-style paths to Windows paths when executing non-MSYS2 programs.
This can be very helpful e.g. when calling `git blame -L /<some-regex>/ ...` so that the regular expression is not mistaken for a Unix-style absolute path and transformed.
However, setting that environment variable globally is prone to wreak havoc, and we should warn loudly when detecting this situation.
This addresses the concern identified as the root cause of https://github.com/git-for-windows/git/issues/3381
=> SDK: warn when MSYS_NO_PATHCONV is set

installer/install.iss, installer/modules.inc.iss
The GPG agent is started automatically. While running, it prevents the corresponding files from being replaced. Therefore, it has to be stopped before upgrading Git for Windows.
This PR does that, and cleans up a bit more while in the neighborhood.
=> Teach the installer that it is relatively safe to terminate any running GPG agent

git-extra/wordpad
When wordpad path has spaces (ex: C:\Program Files\Windows NT\),
invoking the binary will fail.
Add quotes around the $WORDPAD variable to avoid that.
Signed-off-by: Carlo Marcelo Arenas Belón <carenas@gmail.com>
=> git-extra/wordpad: teach wordpad how to deal with spaces in path

git-extra/git-update-git-for-windows
I am trying to make the microsoft/git fork skip the recently-seen check,
allowing us to prompt users daily for upgrade. This turns the toast
notification from a "no, I don't ever want this version" to a "no, I
don't want to upgrade right now; reminde me tomorrow".
The way to make this work differently in microsoft/git is to change this
script during our build. For some reason, I am struggling to replace the
line
recently_seen="$(get_recently_seen)"
during a GitHub Actions workflow, even though my 'sed' invocation works
on my machine. There are existing steps that do an _insertion_ of lines
which I can use to my advantage. The critical thing is that I will
initialize the 'use_recently_seen' variable as non-empty.
By adding a check to see if 'use_recently_seen' is empty, we can
maintain the …
=> git-update-git-for-windows: optionally skip recently-seen

installer/install.iss
They also include a `bin\code` bash script which seems to work, executing a `.cmd` doesn't seem to work for some reason.
This fixes https://github.com/git-for-windows/git/issues/3471
=> Hopefully fix git-for-windows/git#3471

git-extra/inputrc
This should fix issue git-for-windows/git#3254, seen on Windows 10 in the "plain console" terminal (i. e. in "ConHost bash").
Technical details are given in the commit message.
=> fix: make shift+insert do Paste in ConHost bash again

installer/install.iss
When testing the 2.34.0 installer, I saw this confusing page of the wizard:
Changing the selection to GCM Core got me this error after the rest of everything was installed:
By using `--replace-all`, we get rid of this error.
The Wizard page's default setting might still be incorrect. My system config had multiple values because GCM configured it for the system, but used an exact path to the executable instead of just `manager-core`.
```
$ git config --show-origin --get-all credential.helper
file:C:/Program Files/Git/etc/gitconfig manager-core
file:C:/Program Files/Git/etc/gitconfig
file:C:/Program Files/Git/etc/gitconfig C:/Program\ Files\ \(x86\)/Git\ Credential\ Manager\ Core/git-credential-manager-core
file:C:/Users/dstolee/.gitconfig
file:C:/Users/dstolee/.gitconfig        C:/Program\ …
```
=> install.iss: use --replace-all when setting config values

installer/install.iss
This previously had this compile error:
Error on line 858 in C:\(...)\install.iss: Column 33:
Identifier expected
The reason we didn't catch this earlier was because we had inserted some
logging that changed the nature of this if/else to have begin/end
blocks.
Fixes the bug introduced by #390.
=> install.iss: fix if/else syntax

git-extra/git-update-git-for-windows
Recent versions of Git-for-Windows have .rc versions rather than the
-rc versions used previously.
Accept both dash and dotted forms of release candidate version strings,
and add tests, for the .rc version.
This fixes git-for-windows/git#1843
=> update-git-for-windows: accept both .rc and -rc versions

.github/workflows/main.yml, git-extra/PKGBUILD
The PR build will try to build every package whose code has been touched by the PR.
It also adds a `check` to the build definition of the `git-extra` package: we now verify that the version comparison in `git update-git-for-windows` works as expected.
=> Add a PR build definition

.github/workflows/main.yml, installer/install.iss, mingw-w64-git-credential-manager-core/PKGBUILD, please.sh
Git Credential Manager moved recently. Let's accommodate for this move.
While at it, use this splendid opportunity to enhance our PR workflow to also build the installer/portable/etc artifacts touched by PRs (this is a splendid opportunity because the `installer/` files are touched by this PR).
=> Git Credential Manager has a new home

msi/release.sh, portable/release.sh
In [an unrelated PR](https://github.com/git-for-windows/build-extra/pull/394), the CI failed in three jobs: one job failed as expected (because something needs to change elsewhere before it can possibly succeed), but two jobs failed unexpectedly. This PR fixes those two.
=> ci: fix building portable/ and msi/

ReleaseNotes.md
While not every user reads the release notes, this should at least help to
reduce the fallout from the planned bash update.
=> Mention upcoming bash update in release notes

.github/workflows/main.yml
Avoid [a bogus error](https://github.com/git-for-windows/build-extra/actions/runs/1780156306):
> Error when evaluating 'strategy' for job 'build-artifacts'. .github/workflows/main.yml (Line: 63, Col: 20): Matrix vector 'directory' does not contain any values
=> ci: avoid a bogus error when no packages/artifacts need to be built

git-extra/PKGBUILD, git-extra/vimrc
As reported in https://github.com/git-for-windows/git/issues/3725, by mistake we set `fileencodings` instead of `fileencoding` (note the `s` at the end).
=> git-extra(vimrc): only default to UTF-8, don't enforce it

ReleaseNotes.md
This moves up the Bash v5.x warning and starts warning about the imminent end of support for Windows Vista, as well as about the end of Windows 7/8 support early next year.
=> Warn about end of Windows Vista support

please.sh
At some point between April 8 and April 11, 2022, the default file extension for source packages created with `makepkg-mingw --allsource` changed from `.src.tar.gz` to `.src.zst`. This broke the subsequent checks in `please.sh build_mingw_w64_git --build-src-pkg` for the source package, as a file with the expected `.src.tar.gz` extension was not found. The result is that this issue blocks _any_ successful completion of the "[Git Artifacts](https://dev.azure.com/git-for-windows/git/_build?definitionId=34&_a=summary)" pipeline, and therefore needs to be fixed before `v2.36.0`.
Like what was done to force the `tar.xz` default on normal packages with `PKGEXT` (c804266 (Force the Pacman packages back to use xz, 2020-01-22)), we set the `SRCEXT` to `.src.tar.gz` to force the file format we …
=> Force Pacman source package to use .src.tar.gz extension

mingw-w64-git-credential-manager/PKGBUILD
At long last, we do the same with Git Credential Manager as did with Git LFS in a57279dd9: we move its executables into the regular `/mingw64/bin/` directory (or `/mingw32/bin/` in i686 setups).
This provides for a cleaner separation between the non-built-in Git commands that are part of core Git (which are supposed to live in Git's exec path) and third-party commands such as Git LFS, Git Credential Manager, or even Git for Windows' `git update-git-for-windows` and `git credential-helper-selector`.
It will also open the door for addressing https://github.com/git-for-windows/git/discussions/3668 by teaching Git an option to override the standard `PATH` search behavior for third-party Git commands only (current idea is to look through `PATH` and not use the first, but the one with the most …
=> Move Git Credential Manager out of Git's exec path

installer/install.iss
We already require Fx4.6.1, but the installer checks for Fx4.5.1
Signed-off-by: Zak Kohler <git@y2kbugger.com>
I used the _lower_ of the two 4.6.1 checks as that is how 4.5.1 was done previously.
@mjcheetham 
> .NET Framework 4.6.1
> On Windows 10 November Update systems: 394254
> On all other Windows operating systems (including Windows 10): 394271
=> installer: bump NetFx version requirement from 4.5.1 -> 4.6.1

git-extra/git-extra.install.in
We had to re-enable them in b46fba6f4 (git-extra: re-enable some SSHv1 protocols, 2017-10-12) after an OpenSSH upgrade disabled them.
The reason why we had to re-enable those ciphers is gone now, though: Azure Repos understand newer (safer) ciphers.
=> git-extra: disable CBC ciphers in ssh_config again

.github/workflows/main.yml, make-file-list.sh
The "dashed executables" of Git are hard-linked versions of the `git` executable which are provided for built-in commands, for backwards-compatibility.
Since 7cedbf7a5 (sdk init git: skip hard-linking the built-ins by default, 2020-12-01), we skip building (and hence installing) these
dashed executables.
Let's handle this situtation gracefully.
This fixes https://github.com/git-for-windows/git/issues/3888
=> installer/portable/mingit: gracefully omit missing dashed executables

.github/workflows/main.yml, make-file-list.sh, please.sh
The `create-sdk-artifact` subcommand of the `please.sh` script is designed to help Git for Windows generate the various subsets of its SDK that are used in the automation that helps run this project relatively smoothly.
With this PR, we make this a bit smoother, most importantly by ensuring via CI/PR builds that whenever the code is changed, the SDK artifacts still build.
=> A couple of `create-sdk-artifact` improvements

please.sh
Every once in a while, the Git maintainer rotates GPG keys and the `junio-gpg-pub` tag gets force-pushed. As a consequence, the subsequent fetches from forks that have not updated the tag yet will fail, as was
the case when [trying to build Git for Windows v2.37.0-rc0](https://dev.azure.com/git-for-windows/git/_build/results?buildId=100997&view=logs&j=5437d6e9-5c1a-5300-9fd3-4614558e3141&t=025cebf6-6a22-5c04-7eaa-c59935a42109&l=612):
```
[...]
+ case "$branch_to_use" in
+ git '--git-dir=D:\a\1\s\git-sdk-64-build-installers/usr/src/MINGW-packages/mingw-w64-git/src/git/.git' fetch --tags https://github.com/mjcheetham/git rebase-to-2.37.0-rc0
From https://github.com/mjcheetham/git
* branch                  rebase-to-2.37.0-rc0 -> FETCH_HEAD
! [rejected]              junio-gpg-pub -> …
```
=> Make building Git artifacts more robust

ReleaseNotes.md, please.sh
The release notes for v2.37.0-rc0 link to [api.github.com](https://api.github.com/repos/PhilipHazel/pcre2/releases/latest), that's not designed for human consumption. We can do better.
=> Link PCRE2 changelog in release notes

.github/workflows/main.yml, check-for-missing-dlls.sh, make-file-list.sh, please.sh
This PR brings a couple of enhancements, most notably a CI/PR build definition that ensures that the `check-for-missing-dlls.sh` script is _actually_ run, and it does fail when missing or unused DLLs are detected in the set of files destined to be included in Git for Windows' artifacts.
=> Check for missing dlls updates

.github/workflows/main.yml, installer/release.sh, make-file-list.sh, please.sh
I stupidly introduced a bug by pushing directly to `main` ;-) And now I am going to fix the same bug.
=> create-sdk-artifact build-installers: make sure that `/tmp/` exists

make-file-list.sh
As discussed in https://github.com/git-for-windows/MSYS2-packages/pull/55#issuecomment-1156092406 we experimented with a Tig build that uses PCRE2 instead of PCRE. Since this experiment came out with a mere 0.1MB increase of the installer, we're going forward with that switch.
=> installer/portable: accommodate for Tig now linking to PCRE2

make-file-list.sh
We do not ship with the pager called `more`, therefore `zmore` and `bzmore` cannot work. Let's stop shipping them.
This addresses https://github.com/git-for-windows/git/issues/3958
=> installer/portable: drop zmore/bzmore

ReleaseNotes.md, installer/install.iss
For a while now, we announced that Bash will be upgraded. I just did that, the next snapshot will have that change.
Let's mention that in the release notes.
While at it, also drop Windows Vista support as announced earlier, and mention that Git for Windows will drop Windows 7/Windows 8 support soon as well.
=> Release Notes: copy-edit the Bash/Vista/Windows 7/Windows 8 bits

mingw-w64-git-lfs/PKGBUILD
I added ARM64 support to `git-lfs` [a few months ago](https://github.com/git-lfs/git-lfs/pulls?q=is%3Apr+author%3Adennisameling), so let's use it as part of Git for Windows' journey to ARM64 support.
Tested with `MINGW_ARCH=clangarm64 makepkg-mingw -i` and things work as expected:
```
$ git-lfs --version
git-lfs/3.2.0 (GitHub; windows arm64; go 1.18.2)
```
=> mingw-w64-git-lfs: add ARM64 support

mingw-w64-wintoast/PKGBUILD
Needs https://github.com/git-for-windows/WinToast/pull/2 to be merged first
Visual Studio has ARM64 support since the 2017 edition. Let's add support for that architecture in G4W's implementation.
Signed-off-by: Dennis Ameling <dennis@dennisameling.com>
=> wintoast: add ARM64 support

git-extra/git-extra.install, git-extra/gitconfig
This brings color to the people without the complexities of the higher number of configs.
Relates to git-for-windows/git#4095
Signed-off-by: Morten Minde Neergaard <169057+xim@users.noreply.github.com>
=> Set the config color.ui rather than individual configs

check-for-missing-dlls.sh, make-file-list.sh
With the upgrade to mingw-w64-git v2.39.0-rc0, this build started failing, see e.g. [here](https://github.com/git-for-windows/git-sdk-64/actions/runs/3537444656/jobs/5937421607).
The culprit is that pesky `libssp-0.dll` which used to be required for `-fstack-protector` (i.e. GCC's stack-smashing protector), but is no longer needed _when compiling with a newer mingw-w64-gcc_.
The fix is a little tricky because we essentially have to make sure that `git.exe` does not require the `libssp-0.dll` before excluding that file.
=> Fix the `check-for-missing-dlls` build

.github/workflows/main.yml, git-extra/PKGBUILD, git-extra/git-extra.install, git-extra/git-extra.install.in
This is a follow-up for https://github.com/git-for-windows/build-extra/pull/442 (which did not fix our problem completely).
It supersedes https://github.com/git-for-windows/build-extra/pull/447, using a branch in the same repository so that we can branch-deploy.
=> git-extra: set the config color.ui also in existing /etc/gitconfig

.github/workflows/add-release-note.yml, ReleaseNotes.md, add-release-note.js
Implementing this as a relatively easy-to-use workflow is step 1. At some stage, I want to end up with a solution where a member of the Git for Windows team can simply add a comment of the form `/relnote <type> <message>` to a PR and have this workflow triggered automatically.
[This](https://github.com/dscho/build-extra/actions/runs/3548059031) is the workflow that added the release note about MinTTY, and [this](https://github.com/dscho/build-extra/actions/runs/3548082900) is the one that talks about Bash v5.2 patchlevel 12.
=> Automate adding release notes

.github/workflows/main.yml, .gitignore, git-extra/PKGBUILD, git-extra/git-extra.install, git-extra/git-extra.install.in, installer/install.iss, installer/release.sh, make-file-list.sh, please.sh, portable/release.sh
~Needs https://github.com/git-for-windows/MINGW-packages/pull/56~ ✅ merged
~Needs https://github.com/git-for-windows/MINGW-packages/pull/59~ ✅ merged
~Needs https://github.com/git-for-windows/MINGW-packages/pull/58~ ✅ merged
~Needs https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/397~ ✅ merged
~Needs https://github.com/git-for-windows/git/pull/3916~ ✅ merged
~Needs https://github.com/msys2/MINGW-packages/pull/13787~ ✅ merged
~Needs https://github.com/git-for-windows/MINGW-packages/pull/57~ ✅ merged
~Needs https://github.com/git-for-windows/build-extra/pull/440~ ✅ merged
On an ARM64 device, do the following:
- Install the `git-sdk-64`
- Make sure you create the `clangarm64` folder and start the SDK with `MSYSTEM=clangarm64`, as well as install tools like the Clang …
=> portable + installer: add CLANGARM64 support

installer/modules.inc.iss
Signed-off-by: Jean-Michel Mercier [jeanmichel.mercier@newsbridge.io](mailto:jeanmichel.mercier@newsbridge.io
This PR fix the detection of running executable as on current version of Windows, the Process.Name may ends with ` .exe` which make the comprison fails, and the processes are not marked to be terminated.
=> Issue 4172: handle processes names ending with .exe

git-extra/PKGBUILD
Following up on [this discussion](https://github.com/git-for-windows/build-extra/pull/452#discussion_r1052009722).
Until now, the `git-extra` package was published under that exact name. However, it's _actually_ a MINGW package which installs things both in e.g. `/mingw64/bin` and `/etc/profile.d`. This is problematic for GfW's upcoming arm64 support, which uses the x64 MSYS shell, so it'll need its own package. At the same time, packages for multiple architectures can't be installed side-by-side like other MINGW-packages, as this one writes to shared folders like `/etc/profile.d` as well. Therefore we mark them as conflicting each other.
With this change, we'll publish the following packages side by side, so the repos will look like this:
- `git-for-windows/git-extra` (old)
- …
=> git-extra: publish both with and without MINGW prefix

sdk-installer/release.sh, sdk-installer/setup-git-sdk.bat
I'll leave this in draft until the new SDK is available on https://github.com/git-for-windows/git-sdk-arm64, but I just want to confirm that I got this to work with "my" https://github.com/dennisameling/git-sdk-arm64:
Installer:
It's using the native arm64 `git.exe` from the `mini` folder:
And there we are! A native Git for Windows arm64 SDK!
Here's the installer artifact that downloads the SDK from https://github.com/dennisameling/git-sdk-arm64: [git-sdk-installer-1.0.9-arm64.7z.zip](https://github.com/git-for-windows/build-extra/files/10262464/git-sdk-installer-1.0.9-arm64.7z.zip)
=> Update `sdk-installer` to support arm64 SDK

signtool.sh
I ran into an issue with my pipeline where [it was hanging](https://github.com/dennisameling/git/actions/runs/3758239394/jobs/6387153640) on the `git signtool` command. After some checks I found that the `signtool.sh` file didn't have logic yet for `clangarm64`, which is most likely the culprit here.
Now that [upstream MSYS2 has support for osslsigncode.exe](https://github.com/msys2/MINGW-packages/pull/14671) on `clangarm64` , let's leverage it here as the git-sdk-arm64 doesn't have any `mingw64` or `mingw32` packages anymore.
=> signtool.sh: add support for arm64 osslsigncode

pacman-helper.sh
This should be enough to get that part of the deployment working. The idea is that we will have two new package indices, [a full one](https://wingit.blob.core.windows.net/aarch64/git-for-windows.db) and [a MINGW-only one](https://wingit.blob.core.windows.net/aarch64/git-for-windows-aarch64.db). Until the time when Cygwin starts supporting Windows/ARM64, these will contain the same set of packages.
The idea is that we can then set up `/etc/pacman.conf` in `git-sdk-arm64` to contain these lines:
```ini
[git-for-windows]
Server = https://wingit.blob.core.windows.net/x86-64
[git-for-windows-aarch64]
Server = https://wingit.blob.core.windows.net/aarch64
```
=> Prepare for uploading Pacman packages targeting Windows/ARM64

downgrade-pacman-package.sh
We just downgraded a couple of packages to accommodate for Git for Windows sticking to OpenSSL v1.1.x while MSYS2 moved on to OpenSSL v3.x
Unfortunately, an upgrade of the `pacman` package undid this, so we had to redo it.
Here is a script that was used to redo it. It takes as first parameter a shell scriptlet that tests whether the issue that needed to be fixed was actually fixed, followed by a list of packages to downgrade to the previous version. This script was used to auto-generate https://github.com/git-for-windows/git-sdk-64/commit/4c5ca7dbd83, by calling
/usr/src/build-extra/downgrade-pacman-package.sh \
'bsdtar -h || test $? != 127' \
bsdcpio bsdtar libarchive libserf libssh2 rsync
This closes https://github.com/git-for-windows/git/issues/4197.
=> Add a script to downgrade Pacman packages

make-file-list.sh
This fixes the problem pointed out here: https://github.com/git-for-windows/git-sdk-64/actions/runs/3889278102/jobs/6637401828
=> make-file-list: `file.exe` now depends on LZMA

make-file-list.sh
ncurses has provided ms-terminal terminfo since 2019-06-30, according to https://invisible-island.net/ncurses/NEWS.html#t20190630
Signed-off-by: Lauri Tirkkonen <lauri@hacktheplanet.fi>
=> make-file-list: include ms-terminal terminfo

.github/workflows/main.yml, installer/install.iss
This is a follow-up for https://github.com/git-for-windows/git/issues/4230
=> installer: accommodate for the new location of `ca-bundle.crt`

commit-msys2.sh, git-extra/PKGBUILD, git-extra/update-via-pacman.bat.in, please.sh
This depends on #457 being merged first, as it removes a lot of code that we'd otherwise have to update.
I used the list of files that need updating from [this comment](https://github.com/git-for-windows/git-for-windows-automation/pull/5#issuecomment-1362580886) (thanks @dscho!)
=> Start using new git-extra prefix

get-sources.sh, make-file-list.sh
~⚠️ This needs #457 to be merged first~ ✅ 
~⚠️ This needs #461 to be merged first~ ✅ 
I used the list of files that need updating from [this comment](https://github.com/git-for-windows/git-for-windows-automation/pull/5#issuecomment-1362580886) (thanks @dscho!)
Let's leave the rename of the `git-extra` folder to `mingw-w64-git-extra` for a follow-up PR.
Important note regarding Wiki updates: the updates to the wiki currently live on a branch that are not accessible through GitHub's UI. To see them, do the following:
```
git clone https://github.com/git-for-windows/git.wiki.git
git checkout update-git-extra-docs
```
As we can't create a PR for the changes from that branch, we'll have to commit straight to the `main` branch if all looks good. CC @dscho
=> Start using new git-extra prefix (follow-up)

make-file-list.sh
The entire point of the BusyBox variant of MinGit is to avoid having to use MSYS2 resources unnecessarily.
But `sh.exe` slipped through the net, by virtue of being listed in the `sh` dependency (provided by `bash`) that comes in via openssh -> heimdal -> heimdal-libs -> libedit -> sh.
This was pointed out in
https://github.com/git-for-windows/git/issues/3285#issuecomment-1396543785
Let's exclude it specifically.
=> mingit(BusyBox): do exclude Bash

please.sh
This partially addresses the issues pointed out in https://github.com/git-for-windows/build-extra/pull/471.
=> Prepare `please.sh` for building the 32-bit mingw-w64-git in a 32-bit SDK

please.sh
Git for Windows's toolchain is moving away from "bitness" as it doesn't support arm64. See the attached discussion for more details.
Ref: https://github.com/git-for-windows/git/discussions/4203
=> please.sh: teach `create_sdk_artifact` to use `architecture` instead of `bitness`

please.sh
I had totally missed in my review that the default was for `bitness=auto`, and hence `./please.sh create-sdk-artifact build-installers` would automatically pick the appropriate bitness. That default logic was lost, but it is really, really nice to have. Let's have it again, this time with `architecture=auto`.
=> create-sdk-artifact: automatically choose appropriate architecture

gnupg-with-gpgkey.sh
In Git for Windows, we explicitly forbit Git from passing the `--status-fd=2` option to GPG. But on Ubuntu, that option is passed, and it is rather crucial because Git reads the status from `stderr` and is a bit miffed if it does not get any status update there. The symptom is:
```
error: gpg failed to sign the data
error: unable to sign the tag
```
Let's prepare the script to allow for that option to be passed (and also allow for that option _not_ to be passed).
This should fix the problem reported [here](https://github.com/git-for-windows/git-for-windows-automation/pull/22#discussion_r1097837166).
=> gnupg-with-gpgkey: allow running on Ubuntu

pacman-helper.sh
This works around the breakage reported at https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/590#issuecomment-1420415975
=> pacman-helper quick_add: do handle symbolic links

git-extra/PKGBUILD, git-extra/git-extra.install, git-extra/git-extra.install.in
In https://github.com/git-for-windows/git-sdk-64/commit/40af5e29d1efdfb384e25b21891edc64a254099f, the `filesystem` package got updated, which contains the `/clangarm64` directory (which contains quite a few subdirectories, but no files).
This fooled the post-install script of `git-extra` into believing that git-sdk-64 actually targets Windows/ARM64 and hence it added Git for Windows' aarch64 Pacman repository.
I [manually reverted](https://github.com/git-for-windows/git-sdk-64/commit/cce08432ac15f6d68b9b5a2b4a5a7ee4e3823084) that to _not_ register the aarch64 Pacman repository.
However, the next update of the `filesystem` would trigger the same issue.
Let's make the post-install script of `git-extra` smarter so that it does not get fooled anymore.
=> Really only add the aarch64 Pacman repository for git-sdk-arm64

ReleaseNotes.md, installer/install.iss
As per https://github.com/git-for-windows/git/issues/4279, Git for Windows is deprecating the 32-bit variant. Let's teach the installer to detect when a user is installing this variant and show an appropriate warning in that case. On a 32-bit Windows, they will see this type of dialog box:
On a 64-bit Windows, they will see this dialog box:
=> installer: warn about 32-bit deprecation

git-extra/PKGBUILD, git-extra/git-extra.install, git-extra/git-extra.install.in
This faulty quoting somehow slipped in and for some reason only showed up yesterday in [the automated builds](https://github.com/git-for-windows/git-sdk-64/actions/runs/4268074874/jobs/7430553454#step:6:1034):
> ```
> /var/lib/pacman/local/mingw-w64-x86_64-git-extra-1.1.632.0366f1328-1/install: line 292: unexpected EOF while looking for matching ``'
```
=> Fix git extra.install quoting

add-release-note.js, please.sh
This PR is designed to fix the unfortunate short release note pointed out in https://github.com/git-for-windows/git/pull/4316#issuecomment-1446624712 (see e.g. https://lore.kernel.org/git/20230227162638.3393-1-johannes.schindelin@gmx.de/T/#u).
=> _Do_ use add-release-note.js

pacman-helper.sh, wingit-snapshot-helper.sh
When uploading Pacman packages, we have to take care to stop concurrent uploads from interfering with each other. We do that by [acquiring a "lease" to the `git-for-windows.db` file](https://github.com/git-for-windows/build-extra/blob/a5129d3495731b44f8c3023efbbadcd327586fd3/pacman-helper.sh#L621-L623): Once that lease is acquired by one of the uploading workflow runs, it cannot be acquired by another one until the first one is done and [releases that lease](https://github.com/git-for-windows/build-extra/blob/a5129d3495731b44f8c3023efbbadcd327586fd3/pacman-helper.sh#L725-L728).
I noticed today that [the shiny new `pacman-packages` workflow](https://github.com/git-for-windows/git-for-windows-automation/pull/38) had failed to upload the packages. When I edited the definition and then tried …
=> pacman-helper: add a command to break a lease

README.md
Issue reporting is switched off for the build-extra repository. The Git-for-Windows organisation has many potentially relevant repos for reporting issues. Let's direct queries to the primary repo, rather than say the "SDK" repositories.
While here, clarify that the build-extra repo is a core part of the SDK experience, rather than being the SDK in it's totality.
Fixes: https://github.com/git-for-windows/git/discussions/4355 step 1.
=> README.md: report Issues via our main Git-for-Windows git fork

installer/install.iss
When Installing 32-bit Git for Windows we show a Warning that we're deprecating 32-bit support, but there are two Versions of the 32-bit warning. The Version shown on 32-Bit Windows allows a silent install, while the Version on 64-Bit Windows does not. This is fine on AMD64, but for Windows 10 on ARM64 we don't have a good alternative offer. So show them the same message as we show on i686.
=> installer: allow silent install of 32-bit installer on ARM64

git-extra/PKGBUILD, git-extra/cyg-dlls.sh
This is designed to catch issues like [this one](https://github.com/git-for-windows/MSYS2-packages/pull/99#issuecomment-1529114488) much earlier in the future. Like, before even deploying the package 😀
=> Add a `cyg*.dll` linter

check-for-missing-dlls.sh
Both [x86_64](https://github.com/git-for-windows/git-sdk-64/actions/runs/4878656312/jobs/8704497475) and [i686](https://github.com/git-for-windows/git-sdk-32/actions/runs/4878741237/jobs/8704659507) jobs now complain about the new Avalonia UI stuff in Git Credential Manager. Let's accommodate for that stuff.
=> Fix the `check-for-missing-dlls` runs

check-for-missing-dlls.sh, installer/install.iss, installer/run-checklist.sh, make-file-list.sh, please.sh
The ongoing work to address https://github.com/git-for-windows/git/issues/4350 requires a couple of minor downstream adjustments in `build-extra`. This PR implements those adjustments.
=> Accommodate for the libcurl split

check-for-missing-dlls.sh
It should be shipped with Git for Windows, of course. So let's adjust the `check-for-missing-dlls` script accordingly, just like we have already done for `libcurl-openssl-4.dll`.
This is a follow-up to #502
=> check-for-missing-dll: libcurl-4.dll is not a link-time dependency anymore

post-install.bat
The following snippet in `post-install.bat` attempts to parse Windows' major version number from `ver` builtin command output:
```batchfile
@FOR /F "tokens=4 delims=.[XP " %%i IN ('ver') DO @SET ver=%%i
@IF 10 LEQ %ver% @...
```
However, that code has numerous problems:
- `ver` listing varies between major Windows releases (though Git for Windows' support for these has most likely phased out already) and may not necessarily yield the same amount of tokens, thus it's better to perform a two-step tokenization - string, *then* version
- while the output of `ver` hasn't been found to contain 'poisonous' Batch characters (e.g. <>|&), it's preferred to wrap it in double quotes to prevent the contents 'escaping' into another command and use `~` during assignment should it contain double quotes …
=> Parse Windows' version correctly in post-install script

check-for-missing-dlls.sh
There is a new `.dll` file that the `check-for-missing-dlls` script did not anticipate yet. It is _not_ unused, it's just impossible for that script to know because it only looks at other `.dll` and `.exe` files looking for compile dependencies...
Symptom fixed by this PR:
```
unused dll: mingw32/lib/ossl-modules/legacy.dll
```
=> Adjust `check-for-missing-dlls` after the OpenSSL v3.* upgrade

installer/helpers.inc.iss
When the call to `ExecAsOriginalUser` fails already, there is no `stdout` nor `stderr` to work with, but there is an error message that we can show to the user, but we haven't. Let's change that.
This should help diagnosing those vexing problems where the installer fails while reconfiguring existing Scalar enlistments.
Sadly, it is too late for v2.41.0 now, but it may help in the future nevertheless.
=> installer: improve error reporting when `ExecAsOriginalUser` fails

installer/install.iss
Windows context menu:
- Git Bash Here -> Open Git Bash here
- Git GUI Here -> Open Git GUI here
P.S. Today I learned what DCO sign-off is. Thank you!
=> Update install.iss: rephrase menu item labels

installer/install.iss, installer/release.sh
As reported in https://github.com/git-for-windows/git/issues/4525, during upgrades the Git for Windows installer may overwrite the current default branch name if it has been set manually in the system config (as opposed to configuring it in the previous Git for Windows installer run).
This PR addresses that by letting the system config override the values from the previous installer run.
=> Installer: detect manually-configured default branch

signtool.sh
In the issue mentioned below, we've been investigating a problem where code signing _sometimes_ hangs on arm64, but not consistently. It seems to hang somewhere around the osslsigncode.exe process. Let's add some verbose logging there to see if it helps us in the debugging process somehow...
Ref: https://github.com/git-for-windows/git/issues/3107#issuecomment-1634695759
=> signtool.sh: add verbose logging to osslsigncode

.github/workflows/main.yml, installer/install.iss
Over in https://github.com/git-for-windows/build-extra/pull/522, I was implementing a relatively straight-forward bug fix and added an extra precaution to verify via `run-checklist.sh` that the installer works as intended.
Guess how big my surprise was when not only the [`sdk-artifacts (build-installers, 32)` job failed](https://github.com/git-for-windows/build-extra/actions/runs/5961265753/job/16170153237?pr=522#logs) (and _only_ that one, the 64-bit one was fine!), but when I went down a lengthy rabbit hole once I realized that the silent installation of the 32-bit Git for Windows that is part of the validation _failed_, and must have done so ever since c800a3f6004dc0690ec9bcf0ef79f696f53eeb66, i.e. for over half a year!
Turns out that we did not, in fact, validate what we thought we …
=> Fix the PR build installing and validating the 32-bit flavor of Git for Windows

.github/workflows/main.yml, installer/checklist.txt, installer/install.iss, installer/run-checklist.sh
As reported in https://github.com/git-for-windows/git/issues/4571, the Pseudo Console support checkbox does the exact opposite of what it is intended to do.
Turns out that this bug has been with us since Git for Windows v2.41.0, i.e. since June 1st 2023 (or, if you count the pre-releases, since since May 17th, 2023).
This PR fixes the logic and adds a check to prevent regressions in the future.
=> installer: fix the broken "Enable Pseudo Console Support" option

make-file-list.sh
As pointed out by [the git-sdk-64 CI run](https://github.com/git-for-windows/git-sdk-64/actions/runs/6104874310/job/16567540462) as well as by [the git-sdk-32 CI run](https://github.com/git-for-windows/git-sdk-32/actions/runs/6104973449/job/16567771427), we were newly missing a DLL. This fixes that.
=> installer/portable: include libbrotlienc

please.sh
This is a brown paper bag fix for #527
=> build-installers: do include the 7-Zip DLL

installer/environment.inc.iss, installer/install.iss
Partially addresses https://github.com/git-for-windows/git/issues/4604.
=> installer: sanitize GIT_* environment variables

.github/workflows/main.yml, aslr-manager.ps1, installer/install.iss, make-file-list.sh
Implemented a workaround for mandatory ASLR in the installer by asking the user if they wish to add security exceptions so that the executables in the "usr/bin" directory and Git Bash function correctly on Windows systems with mandatory ASLR enabled which is a Windows security feature that is disabled by default.
- [https://learn.microsoft.com/microsoft-365/security/defender-endpoint/exploit-protection-reference?view=o365-worldwide#force-randomization-for-images-mandatory-aslr](https://learn.microsoft.com/microsoft-365/security/defender-endpoint/exploit-protection-reference?view=o365-worldwide#force-randomization-for-images-mandatory-aslr)
- https://github.com/git-for-windows/git/issues/1412
- https://github.com/mintty/wsltty/issues/6#issuecomment-415961012
The aforementioned issues are …
=> Implemented a workaround for mandatory ASLR

installer/install.iss
Fixes https://github.com/git-for-windows/git/issues/4407
We stated that "Merge" would be the default `git pull` behavior but it is not.  The default mode is in fact "ff-only" and we follow here.
=> Clarify that `ff-only` is git's default pull behavior

apply-from-lore.sh
The public-inbox system is used for all kinds of projects that still use that quaint mailing-list centric patch contribution process, not only for Git.
Cygwin, for example, uses it, too.
The `apply-from-lore.sh` script already allowed applying individual patches from other projects' public-inbox URLs.
With this change, it is now also possible to apply patch _series_ from such public-inbox URLs, such as
https://inbox.sourceware.org/cygwin-patches/20230712120804.2992142-1-corinna-cygwin@cygwin.com/
I used this modified version a couple of times when upstreaming MSYS2 runtime patches, and could imagine that it comes in handy for other contributors, too.
=> apply-from-lore: allow specifying non-Git URLs

please.sh
As @rimrul noticed, between v2.43.0-rc1 and v2.43.0-rc2 we [did not reset `pkgrel=1`](https://github.com/git-for-windows/git/pull/4692#issuecomment-1817775282).
This is part 1 of the two-parter to address this (and I plan on merging this today, [in time for v2.43.0 final](https://gh.io/gitCal)).
=> please.sh build-mingw-w64-git: optionally reset `pkgrel`

installer/install.iss
As reported in https://github.com/git-for-windows/git/issues/4727, with Windows' switch of the default system font a couple labels are now cut off. Let's fix this by re-wrapping the text accordingly.
=> installer: avoid cut-off text

please.sh
This script is already used by the `sync` jobs that keep the Git for Windows SDKs up to date.
We're about to use the same script in the automation that builds Git for Windows' packages, so let's make sure that this script is available in those scenarios.
=> create-sdk-artifact(build installers): include `update-via-pacman.ps1`

make-file-list.sh
Resolves git-for-windows/git#4806
Verified as working by running the following in sdk
```
/usr/src/build-extra$ ./mingit/release.sh 0-test
```
Only `mingw64/lib/exec/git-core/mergetools/git-difftool--helper` is added to `MinGit-0-test-64-bit.zip`
=> Include git-difftool--helper in minimal git

git-extra/PKGBUILD
The initial maintainer of this pkg is by far the wrong person to be written in the maintainer slug. Let's add @dscho here to correctly state who is maintaining the `git-extra` package.
=> git-extra: Correct maintainer slug

portable/release.sh
In https://github.com/git-for-windows/git/issues/4955 it was pointed out that the i686 version ("32-bit") of Portable Git v2.45.1 is missing the `package-versions.txt` file.
While it is unclear why that happened (the logs of the -- embargoed -- build do not reveal any clue about this issue), let's at least ensure that it does not happen again.
/cc @mcgitty
=> portable: make sure that `package-versions.txt` is included

git-extra/PKGBUILD, git-extra/getgit
This reg query result for the user path environment variable could potentially get truncated if a space was contained anywhere inside the path variable. This is especially problematic because this incorrect value is then written back, effectively destroying part of the users path.
For example with path containing `D:\important\entry;C:\my\very            spacey\path`:
Before: `reg query "HKEY_CURRENT_USER\Environment" //v Path 2>/dev/null | awk 'NR==3 {print $NF}'` -> `spacey\path`
After: `reg query "HKEY_CURRENT_USER\Environment" //v Path 2>/dev/null | awk 'NR==3 {print}' | cut -d ' ' -f 13-` -> `D:\important\entry;C:\my\very            spacey\path`
=> getgit: Fix user path reg query result potentially getting truncated

please.sh
This patch is a companion of
https://github.com/git-for-windows/MINGW-packages/pull/119: Git for Windows will use regular `asciidoctor`, not the AsciiDoctor extensions.
=> please.sh pkg_build: switch to regular asciidoctor

please.sh
We used to include `gettext` in the `build-installers` SDK artifact, but more by mistake than on purpose. We need to include it again, this time on purpose, to fix https://github.com/git-for-windows/git/issues/4952.
=> Avoid several warnings while building `mingw-w64-git*`

make-file-list.sh
The `sshd.exe` file is already excluded from MinGit for quite a while. As of OpenSSH 9.8, there is a new `sshd-session.exe`, which also needs to be excluded.
This new file is part of an ongoing effort to split `sshd` further, see https://github.com/openssh/openssh-portable/commit/03e3de416ed7c34faeb692967737be4a7bbe2eb5 for more details. This was mentioned in some fashion in [the release notes](https://www.openssh.com/releasenotes.html#9.8p1):
> * [sshd(8)](https://man.openbsd.org/sshd.8): the server has been split into a listener binary, [sshd(8)](https://man.openbsd.org/sshd.8),
and a per-session binary "sshd-session". This allows for a much
smaller listener binary, as it no longer needs to support the SSH
protocol. As part of this work, support for disabling privilege
separation (which …
=> mingit: exclude new sshd executable

ReleaseNotes.md
Version 2.44 and 2.45 both claimed to be the "last version" to support Win 7/8. Fix by changing the 2.44 text to match earlier releases.
Remove duplicate deprecation warnings from point release notes, since these aren't really "changes since the last release".
=> Reduce redundancy/clarify Win 7/8/32-bit deprecation notices.

pacman-helper.sh
The idea is of course to help https://github.com/git-for-windows/git-for-windows-automation/pull/86
=> Let `pacman-helper.sh` run in Linux

installer/helpers.inc.iss
When running the installer of `microsoft/git` v2.45.2.vfs.0.2, it is possible to run into this error:
Line 3401: Could not reconfigure Scalar enlistment.
The most likely reason is a recent change in InnoSetup (and therefore affects both `microsoft/git` and regular Git for Windows), concretely: [this one](https://github.com/jrsoftware/issrc/commit/ba9bdedad772c429dee700957b78aae0d1c8dab3#diff-ba50e25972bfa9da0e0159b1fae6c5921f46440eebc624cb9401093c1bc32804R181).
Essentially, when creating a safe directory, InnoSetup now protects it via reduced permissions (e.g. allowing the original user who started the installer only to read, but not write into the directory) if it is in a temporary directory on a local drive.
This is affects e.g. the `ExecSilentlyAsOriginalUser()` function which wants to …
=> installer: fix the `scalar reconfigure --all` invocation

installer/install.iss
It is also recommended only for larger repositories/worktrees. So let's not show the option at all anymore unless it had been enabled in the previous installation and the user is upgrading/reinstalling. And even then, disable it.
This addresses https://github.com/git-for-windows/git/issues/4570, at long last.
This is how the Experimental Options page looks now if the user had the FSMonitor feature enabled previously:
And this is how it looks like in fresh installs or when upgrading from an installation where FSMonitor was disabled:
=> installer: reflect the fact that FSMonitor is no longer experimental

make-file-list.sh
The OpenSSH daemon (i.e. the server-side) is not actually something Git for Windows needs per se, nor wants to support. So let's stop shipping it.
=> installer/portable: exclude `sshd`

installer/install.iss
Without quoting the path, the door is open for executing unintended executables.
This fixes https://github.com/git-for-windows/git/issues/5100.
=> installer(windows terminal): quote path

.github/workflows/main.yml, installer/install.iss, installer/release.sh
There is a function to compare versions both in `git update-git-for-windows` as well as in the installer. Let's validate in our CI builds that both work as intended.
=> Regularly test the version comparison functionality

please.sh
As of e292201a (please.sh: change from bitness to architecture in create_sdk_artifact, 2022-12-28), we want to use the CPU architecture (or equivalent) instead of the "bitness", but there was one forgotten instance that still needs to be fixed.
=> makepkg-git: support Windows/ARM64 better

ReleaseNotes.md
MSYS2 changed the behavior of MINGW executables' wildcard expansion. This has ramifications when spawning a `git.exe` whose argument contains asterisks or question marks.
This does _not_ affect the way wildcards are expanded when calling `git` from Git Bash (or from a shell script) because that expansion is handled by Bash already.
=> Release Notes: mention the change of behavior re: wildcard expansion

installer/install.iss
As of a75602aa0 (installer: hide the "experimental" FSMonitor setting by default, 2024-07-17), the FSMonitor option is hidden from the options page unless the user had enabled it previously.
However, this then left the page blank (or: all options hidden), not a good user experience. So let's skip it if it would appear blank.
This fixes https://github.com/git-for-windows/git/issues/5231.
=> installer: skip Experimental Options page, if empty

installer/install.iss
[As announced in July 2022](https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#changes-since-git-for-windows-v2371-july-12th-2022), Git for Windows is dropping support for these older Windows versions, [following MSYS2's lead](https://github.com/msys2/msys2.github.io/blob/source/web/news.md#2023-01-15---dropping-support-for-windows-7-and-80). Let's make sure that the installer actively blocks the installation process on these versions. The minimal Windows version is now 8.1 (6.3).
Looking ahead: if the minimum version reaches `10.0`, GfW could choose to switch to `CLANG64` instead of the current `MINGW64`, [which is using the more modern `ucrt` C library](https://www.msys2.org/docs/environments/). Our recent work on `CLANGARM64` support paves the way for this …
=> installer: drop support for Windows 7 and 8.0

mingw-w64-cv2pdb/PKGBUILD
[This cv2pdb version](https://github.com/rainers/cv2pdb/releases/tag/v0.53) is supposed to have a much-improved DWARF -> PDB support, which is exactly what we use in Git for Windows.
=> cv2pdb: upgrade to v0.53

installer/install.iss
Commit 8a7ab99 (installer: switch the libcurl default to Secure Channel, 2023-05-15) attempted to change the default libcurl backend for clean new installs to Secure channel, but only adjusted one of two fallbacks in the installer. There is one default value that gets passed to ReplayChoice() to return if it finds no previous choice and one value that gets used if ReplayChoice() returns an unexpected value. 8a7ab99 changed the latter to use Secure Channel, but left the former to default to OpenSSL. Adjust the default value to match the intention of that patch.
This fixes https://github.com/git-for-windows/git/issues/5295
=> installer: really default to Secure Channel

ReleaseNotes.md, please.sh
For almost eight years, Git for Windows' snapshots were hosted at https://wingit.blob.core.windows.net/files/index.html, i.e. on Azure Blobs.
As of a combination of PRs (https://github.com/git-for-windows/git-for-windows-automation/pull/109, https://github.com/git-for-windows/gfw-helper-github-app/pull/117), snapshots are not only now built and deployed via GitHub Actions instead of Azure Pipelines (and ARM64 artifacts are now included, too), they are also hosted [on GitHub](https://github.com/git-for-windows/git-snapshots/releases/), with the main page being hosted [on GitHub Pages](https://github.com/git-for-windows/git-snapshots/commits/gh-pages).
Therefore, the original link now redirects to a new location (which is also a lot easier to remember): …
=> ReleaseNotes/prerelease: use the new Git for Windows snapshots URL

please.sh
The idea of having `git-sdk-*` repositories that track full MSYS2 environments is not only to have a convenient and fast way to bootstrap a build environment in which to build and release Git for Windows, it also enables straight-forward processes for embargoed builds, where we have to "time-travel" back to the state from which the preceding version was built and assembled.
To guarantee that this time traveling continues to work, the build process of a regular Git for Windows release must be prevented from "conveniently" installing missing dependencies; If they are not part of the `git-sdk-*` repository (or not in the `build-installers` sparse checkout), that needs to be changed before releasing, so that the embargoed release process can continue to work as intended.
=> please.sh build-mingw-w64-git: assume that all dependencies are installed

ReleaseNotes.md
It poses a substantial maintenance burden, what with the need not only to keep maintaining Perl, but also subversion (and apr, apr-util, and swig, and the Perl bindings of subversion).
At the same time, less and less `git svn` tickets (and no PRs worth talking about) have trickled in.
Therefore it is a good time to say good-bye to `git svn` and send it off to a cozy, relaxing retirement on the beach. It has served us well and can now go on to enjoy life instead of work.
I'd like this to be part of v2.48.1's release announcement.
=> Release Notes: announce that `git svn` will be phased out

.github/workflows/main.yml, check-for-missing-dlls.sh, git-extra/Makefile, git-extra/PKGBUILD, git-extra/git-extra.install, git-extra/git-extra.install.in, make-file-list.sh, please.sh
As of yesterday, the [`check-for-missing-dlls` job in `git-sdk-32`](https://github.com/git-for-windows/git-sdk-32/actions/workflows/check-for-missing-dlls.yml) is failing, and only in that `git-sdk-*` repository. The culprit is [this monster of a commit](https://github.com/git-for-windows/git-sdk-32/commit/e9756b51a5ffb7dac5948e7a005c520f3a602be2) that you should not try to load in the browser, as GitHub fails thusly:
<details><summary>Here is the commit message in its full glory</summary>
```
Update 169 packages
apr (1.7.0-1 -> 1.7.5-1)
apr-util (1.6.1-1 -> 1.6.3-2)
asciidoc (9.1.0-2 -> 10.2.1-2)
autoconf-wrapper (new: 20240607-1)
autoconf2.13 (2.13-3 -> 2.13-6)
autoconf (2.71-1 -> 2.69-4)
autoconf2.71 (new: 2.71-4)
autoconf2.72 (new: 2.72-3)
autogen (5.18.16-1 -> 5.18.16-5) …
```
=> Fix missing i686 dlls

make-file-list.sh
@jeremyd2019 I basically took your suggestion from https://github.com/git-for-windows/build-extra/pull/591#discussion_r1955266697, ghost-wrote a commit message, and opened this PR. What do you think? Okay?
=> make-file-list.sh: future-proof the `pactree` output parsing

git-extra/PKGBUILD, git-extra/git-extra.install, git-extra/git-extra.install.in
After git-for-windows/MSYS2-packages#219 the extra file is no longer needed.
=> git-extra(i686): remove libunistring workaround

pacman-helper.sh
add an action parameter to the prior quick_add function, and use if checks to see if we are adding or removing.  Provide wrapper functions for quick_add and quick_remove.
For https://github.com/git-for-windows/git-sdk-32/issues/39#issuecomment-2664159567
=> pacman-helper.sh: add quick_remove mode

pacman-helper.sh
The (dual) strategy of the new Pacman repository is to not only publish the latest state in the `x86_64`, `aarch64` and `i686` branches, but also to upload the files in the latest update to a GitHub Release.
Naturally, when adding a new package version, the package archive and its PGP signature need to be included in that Release.
However, when _removing_ a package, the corresponding package archive should of course be omitted ;-)
=> pacman-helper.sh quick_remove: skip uploading package files

make-file-list.sh
It newly depends on `libpcre2-posix-3.dll`; Previously, it depended on PCRE1's `libpcreposix.dll`.
This fixes the failing `check-for-missing-dlls` runs ([x86_64](https://github.com/git-for-windows/git-sdk-64/actions/runs/13490113963), [i686](https://github.com/git-for-windows/git-sdk-32/actions/runs/13490182113)).
=> installer/portable: include new dependency of `odt2txt`

make-file-list.sh, please.sh
As of `filesystem` 2025.02.23-1, that file does not exist anymore. So let's not insist on its presence when building Git for Windows' artifacts.
This fixes [the currently failing `git-artifacts` workflow](https://github.com/git-for-windows/git-sdk-64/actions/runs/13535776680/job/37827746211#step:6:54320).
=> make-file-list: do not expect /etc/bash.bash_logout to exist

pacman-helper.sh
I noticed the latest release created picked up its name from the latest commit to the main branch in the pacman-repo repository, namely "2025-02-26T22-44-26.725080300Z: Merge pull request #1 from git-for-windows/populate-the-readme".  Given that it's very unlikely that the commit(s) on the main branch have anything to do with the releases, just specify the name to be the same as the tagname.
When I use `gh release create` to create releases, in order to suppress this behavior, I have to specify `--title` as well as the tag.  It seems the REST API equivalent is `name`
example:
```
gh release create "$timestamp" --title "$timestamp" --notes "" -R ${{ github.repository }} 
```
(I didn't bother trying to specify empty notes, I think you get the same behavior in the REST api by not specifying …
=> pacman-helper.sh: set release name to be the same as tagname

pacman-helper.sh
The empty file was created as release_notes.txt in the CWD, while it was written to as release-notes.txt in $dir/$arch subdirectories, and ultimately read as release-notes.txt I believe in the CWD again.  Get rid of the ambiguity by always referencing it as
"$dir/release_notes.txt"
=> pacman-helper.sh: fix usage of release notes file

git-extra/PKGBUILD, git-extra/git-extra.install, git-extra/git-extra.install.in
A change in nano v8.2 rendered Git for Windows' logic to enable syntax coloring in `nano` non-functional. Let's fix this, along with a couple other minor things I found on the way.
This fixes https://github.com/git-for-windows/git/issues/5462
=> Fix `nano`'s syntax coloring

ReleaseNotes.md
Ever since the switch from MSys/MinGW to MSYS2/MINGW in 2015, i.e. almost 10 years ago, Git for Windows hasn't bundled the certificates that were specifically mentioned in the release notes.
They were introduced via https://github.com/msysgit/msysgit/issues/37, which is _such_ a blast from a more pleasant past. But since the certificates aren't included any more, we should not claim that we do in the release notes, either.
=> ReleaseNotes: stop mentioning certificates that aren't bundled

ReleaseNotes.md, please.sh
Renamed in https://github.com/git-for-windows/git/commit/1f010d6bdf756129db13d1367c888aa4153f6d87.
=> Adapt to renamed release notes files

installer/install.iss
In https://github.com/git-for-windows/git/issues/5492 I was made aware that `cmd` and `etc` (and in particular, `etc\gitconfig`) are not removed by the uninstaller.
This PR fixes it, and then also adds some defensive programming that _might_ have prevented the (rare?) problem that was the actual reason for said report.
=> Uninstall Git for Windows more thoroughly

ReleaseNotes.md, installer/install.iss, msi/GitProduct.wxs, render-release-notes.sh
As of https://github.com/git-for-windows/git-for-windows.github.io/pull/59, the pages of Git for Windows' wiki have been migrated to https://gitforwindows.org/. Let's avoid using the old links.
=> Replace all links to Git for Windows' (migrated) wiki

installer/install.iss
The proposal to change the term "master" to something else began six years ago. At this point, claiming the change will happen "in the near future" has clearly proven inaccurate.
There are likely other places in Git where similar outdated language still appears, however I think this is the only occurrence in this repository.
=> Update outdated text in install.iss

git-extra/PKGBUILD, git-extra/git-extra.install, git-extra/git-extra.install.in, please.sh
I meant to do this a lot earlier: In February, I started migrating off of the Pacman repository that is hosted in my personal Azure account, to a new Pacman repository that is hosted on GitHub Releases.
With this PR, Git for Windows' SDK is moved over to the new Pacman repository.
Note that the `get-sources.sh` script is left alone, for now, as it will require substantial work (because it is no longer as easy to find the source package for a given package _version_; It will require [using the GitHub REST API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases), probably via `gh` so that the `--jq` option can be used to filter by the desired asset filename).
=> Switch to the new Pacman repository

installer/install.iss
When choosing a custom editor, there is the convenient "Test Custom Editor" button. When clicking it, a file is written and the specified editor is invoked to edit that file. The file is then deleted.
The contents of that file specifically encourage the user to make changes and write the file.
Unfortunately, due to security concerns InnoSetup nowadays restricts the permissions of its temporary directory, which means that the file (which is written by the elevated installer process) is not writable by the (non-elevated) custom editor.
Let's just write the file _next_ to that temporary directory, which is the user's TEMP directory and therefore writable.
This fixes https://github.com/git-for-windows/git/issues/5618.
=> installer: test any custom editor on a _writable_ file

git-extra/PKGBUILD, git-extra/git-extra.install, git-extra/git-extra.install.in
There was [a problem](https://github.com/git-for-windows/git-sdk-64/actions/runs/15201707468/job/42756925883#step:3:105) with the most recent `sync` runs in `git-sdk-64` (and in `git-sdk-arm64`, but not `git-sdk-32`) because the local copy of the Pacman database was still named `git-for-windows.db` instead of `git-for-windows-x86_64.db`.
This fixes that.
It's like the (old) Pacman version that `git-sdk-32` has that allowed it to pass.
=> Rename local pacman db if needed

ReleaseNotes.md, add-release-note.js
I just noticed that the release notes for Git for Windows v2.50.0-rc0 contain multiple entries for the MSYS2 runtime; Fix that.
=> Drop superseded msys2 runtime entries from the release notes

please.sh
In #622, I fixed the NuGet package build, but that fix re-broke the aarch64 installer (and my testing on x64 -- as I have no Windows/ARM64 hardware -- was fooled by an unrelated fix that hid the bug).
=> build-installers: include `/etc/msystem.d` when available

git-extra/astextplain
The fix for https://github.com/git-for-windows/git/issues/5641 broke diffs for plaintext DOC and DOT files:
$ echo Test > test.doc
$ git add test.doc
$ git diff --cached
E: unsupported filetype test.doc
Since `file` correctly identifies the mimetype of such files as `text/plain`, this can be fixed by simply covering this case and printing the file content as it was done previously.
=> astextplain: restore passthrough for plaintext DOC/DOT files

.github/workflows/main.yml, make-file-list.sh
Since https://github.com/msys2/MINGW-packages/pull/24750, the `mingw-w64-gcc-libs` package now has a hard dependency on `mingw-w64-tzdata`. That latter package contains, let's say, _many_ files.
As a consequence, the `7z` invocation to build MinGit would now fail like this:
```
Creating .zip archive
+ cd /
+ 7z a -mx9 [...]
release.sh: line 176: /mingw64/bin/7z: Argument list too long
Error: Process completed with exit code 126.
```
This is the underlying reason for the recent [`git-artifacts` CI failures](https://github.com/git-for-windows/git-sdk-64/actions/workflows/git-artifacts.yml):
Since the new code that makes use of that tzdata explicitly comes with a fall-back to an internal database, let's just skip the tzdata when building MinGit.
=> mingit: exclude the tzdata

ReleaseNotes.md
With this amount of bug fixes, it is high time to release a new version so that Git users can benefit from them. The current plan is to release Git for Windows v2.51.0(2) on this coming Monday, September 29th, 2025.
=> Release Notes: list the many bug fixes in Git for Windows v2.51.0(2)
