git-for-windows/build-extra

profile.d/aliases.sh

Added an `aliases.sh` file in the profile.d folder that has the aliases that were
previously defined in `msysgit/etc/bash_profile`.

new-aliases-file

---

net-installer/setup-git-sdk.bat

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

Net installer sdk forget to install git html doc.

---

README.md

readme: fixed shell code for initial cloning

---

git-extra/inputrc

Complete on Shift-Tab

---

installer/ReleaseNotes.md
portable/root/README.portable

documented --cd-to-home. Removed old

---

installer/ReleaseNotes.md

Signed-off-by: Matt Kraai <kraai@ftbfs.org>

Fix the link to the mtab issue

---

pacman-helper.sh

For housekeeping the _Git for Windows SDK_ installation it would be useful
to have some common pacman snipplets right there to be used. Lets
introduce those snipplets in the build-extra repository.

git-extra: include some usefull sdk-aliases

---

installer/install.iss

Follows-up: https://github.com/git-for-windows/build-extra/pull/101

Remove experimental tag from fscache

---

ReleaseNotes.md

Signed-off-by: Matt Kraai <kraai@ftbfs.org>

Add "General" to "GNU Public License"

---

please.sh

If test_remote_branch is triggered from TravisCI then the branch name
might not be sufficient to identify the commit that TravisCI is
checking. Teach test_remote_branch an optional argument to specify
the exact commit hash that should be build and test. This commit hash
needs to be on the remote-tracking-branch that is specified as
mandatory argument.
/cc @dscho

please.sh: add optional "commit" argument to test_remote_branch

---

please.sh

The output of the default Git test runner is pretty verbose. Clean up
the output to improve readability.
I added no option to disable this cleanup as I can't think of a case
where the verbose output would be useful.
⚠️ **I haven't tested this as I don't have a Windows machine to play with ATM** ⚠️ 
---
This should make the output look like this:
```
make: Entering directory '/c/agent/_work/1/s/t'
rm -f -r 'test-results'
make aggregate-results-and-cleanup
make[1]: Entering directory '/c/agent/_work/1/s/t'
t0000-basic.sh
t0001-init.sh
t0002-gitfile.sh
t0003-attributes.sh
t0004-unwritable.sh
skipped: write-tree should notice unwritable repository (missing SANITY,POSIXPERM of POSIXPERM,SANITY)
skipped: commit should notice unwritable repository (missing SANITY,POSIXPERM of POSIXPERM,SANITY) …
```

please.sh: cleanup test output

---

mingw-w64-git-lfs/PKGBUILD

Details here: https://github.com/git-lfs/git-lfs/releases/tag/v2.1.1

update git-lfs to address security vulnerability

---

installer/install.iss

See https://github.com/git-for-windows/git/issues/1229

installer: Add registry for Windows Libraries

---

make-file-list.sh
sdk-installer/setup-git-sdk.bat

Add to installer Tig: text-mode interface for Git
https://github.com/jonas/tig

Add to installer Tig

---

git-extra/astextplain
git-extra/git-extra.install
git-extra/gitattributes
make-file-list.sh

Use odt2txt to compare libreoffice files
https://github.com/dstosberg/odt2txt
Should I provide a compiled version or ping the maintainer to do so?

Compare openDocument files

---

git-extra/git-extra.install
git-extra/gitattributes
post-install.bat

Fix post install script due to error in  variable expansion

installer: Fix post-install

---

git-extra/git-extra.install.in

As discussed on Gitter.  Hope this change is okay.

git-extra: Check for existence of files to be modified

---

installer/install.iss

installer: always use the Git wrapper for cmd\git-lfs.exe

---

installer/install.iss

The "Good edition" of #180. Fixes git-for-windows/git#1513.
It contains the requested changes:
* `I could imagine that all these commits should be squashed into one`
* `The commit messages should be self-contained`: I'm bad at explaining things, so is better to leave it as-is.
* `Sign-off to the commit message`
cc @dscho

Added VS Code Insiders Support

---

git-extra/create-shortcut.c

Cleanups in create-shortcut.c

---

make-file-list.sh

Long time user, first time contibutor :)
I've solved the ticket here: https://github.com/git-for-windows/git/issues/1362
I have not done anything extra not covered in the ticket. This seems to solve the issue, I have not located any GitWeb content that is not excluded by the simple pattern.
I reference the issue in the body of the commit, let me know if that is considered bad practice.
Thank you for your great work!
Feel free to add feedback, and I will happily rework the patch.

Skip gitweb in Git for Windows

---

ReleaseNotes.md

Signed-off-by: Scott Stafford <scott.stafford@gmail.com>

ReleaseNotes: Clarifying notice of deprecation of Git CMD.

---

git-extra/git-credential-helper-selector.c

Use modern default font for credential helper selector dialog

---

mingw-w64-git-lfs/git-lfs.install

I've messed up the default LFS config in git-for-windows/git#2140, but this should fix it.

Revert "git-lfs: adjust config settings to the latest ones"

---

installer/install.iss

- Test!
- Old install
- New install
- Admin
- Non-admin
- Developer mode disabled

Enable developer mode checking for standard symbolic-link checkbox

---

installer/install.iss

Really upgrade to GCM Core

---

ReleaseNotes.md

Added known issue as suggested https://github.com/git-for-windows/git/issues/2872#issuecomment-757441615

Added known issue about crashes due to Mandatory ASLR

---

installer/exec-with-capture.inc.iss
installer/install.iss

This helps with the Windows Terminal Profile problem (read: it fixes https://github.com/git-for-windows/git/issues/3312), and there is a beginning of addressing the vexing "could not execute cmd.exe" problem.
I also changed the way the uninstallers are called, to allow for pumping messages (making the main window responsive during those phases).
Finally, I added a couple of status messages so that there should no longer be any stretches of time where the user has no idea what is going on behind the scenes.

Some installer improvements

---

installer/install.iss

Signed-off-by: Pavel Moiseenko <19418601+rakleed@users.noreply.github.com>
Closes https://github.com/git-for-windows/git/issues/3319.
I found information about this [here](https://jrsoftware.org/ishelp/index.php?topic=setup_uninstalldisplayname), but I didn't build it myself, since I could not understand some points of the instruction.

Specify name of app in list of installed apps

---

installer/install.iss

Signed-off-by: Sachin Joseph <sachinjoseph@users.noreply.github.com>

Fix casing

---

please.sh

As reported [here](https://github.com/git-for-windows/git-for-windows-automation/pull/22#issuecomment-1421268074), the `installer` artifact for `arm64` couldn't be created completely as `please.sh bundle-pdbs` doesn't support it yet. This PR adds the support.
Example artifact: 
[pdbs-for-git-arm64-2.39.1.windows.1.531.gb3665b1bf4-1.zip](https://github.com/git-for-windows/build-extra/files/10689119/pdbs-for-git-arm64-2.39.1.windows.1.531.gb3665b1bf4-1.zip)

please.sh: make bundle_pdbs arm64-ready

---

pacman-helper.sh

Do some trivial sed escaping of characters that might cause issues in JSON.  This is not comprehensive, but the text in question is controlled by this script and package names and versions being published, so we can reasonably be assured of a limited set of characters being used.  (In fact, it's probably unnecessary to escape quotes and backslashes).   
I noticed that the version of sed has a `-z` option, which nominally makes it operate on `\0`-delimited input instead of `\n`, but effectively removes the need for a loop to special case `\n`.

pacman-helper.sh: compose release body/notes
